DROP TABLE IF EXISTS `playerbots_arena_team_names`;
CREATE TABLE `playerbots_arena_team_names` (
                                               `name_id` mediumint(8) NOT NULL AUTO_INCREMENT UNIQUE,
                                               `name` varchar(24) NOT NULL UNIQUE,
                                               `type` TINYINT(3) NOT NULL,
                                               PRIMARY KEY (`name_id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='Playerbot arena team names';


DELETE FROM `playerbots_arena_team_names`;
INSERT INTO `playerbots_arena_team_names` (`name_id`,`name`, `type`) VALUES
(NULL, 'out of coverage',2),
(NULL, 'Dead or Alive',2),
(NULL, 'Noßrain',2),
(NULL, 'Истребление',2),
(NULL, 'Pieces',2),
(NULL, 'ßurst',2),
(NULL, 'hey im actually not mvp',2),
(NULL, 'Group Therapy',2),
(NULL, 'Outland Elite',2),
(NULL, 'Исчадье Тьмы',2),
(NULL, 'Dun Spetsnaz',2),
(NULL, 'ЧСВ РБГ',2),
(NULL, 'ShameReborn',2),
(NULL, 'TEAM VÉSUVE',2),
(NULL, 'Battle for Apes',2),
(NULL, 'Can You Feel It',2),
(NULL, 'Zero to Hero',2),
(NULL, 'Link Curve',2),
(NULL, 'Project',2),
(NULL, 'Security',2),
(NULL, 'Skill Loading',2),
(NULL, 'Cya Bro',2),
(NULL, 'out of rage',2),
(NULL, 'Improve',2),
(NULL, 'WORST GENERATION',2),
(NULL, 'KFC Fitness Club',2),
(NULL, 'unlucky',2),
(NULL, 'OldStyle',2),
(NULL, 'Walkthrough',2),
(NULL, 'Лё Резистанс',2),
(NULL, 'League of Gladiators',2),
(NULL, 'Practice',2),
(NULL, 'Rofl So Bad',2),
(NULL, 'Synergy',2),
(NULL, 'Que la famille',2),
(NULL, 'Древние баги',2),
(NULL, 'Echo',2),
(NULL, 'KARMA',2),
(NULL, 'Exodus',2),
(NULL, 'Felsenfest',2),
(NULL, 'LifeIsPain',2),
(NULL, 'The Eternal',2),
(NULL, 'Raid Trap',2),
(NULL, 'The Dambusters',2),
(NULL, 'Станция Токсичных',2),
(NULL, 'Cykla Blöt',2),
(NULL, 'Ethics',2),
(NULL, 'Human ZOO',2),
(NULL, 'Mausoleum',2),
(NULL, 'Nashwan GoDs',2),
(NULL, 'PASTIS PETANQUE ARENE',2),
(NULL, 'tweet holinka',2),
(NULL, 'Пять Бутылок Водки',2),
(NULL, 'РЕТРИК РУКИ ПОЛТОРАШКИ',2),
(NULL, 'У беляша',2),
(NULL, 'A M K',2),
(NULL, 'Against The WorId',2),
(NULL, 'Dilemma',2),
(NULL, 'Efficiency',2),
(NULL, 'Halcyon',2),
(NULL, 'I SoliD I',2),
(NULL, 'Impact',2),
(NULL, 'Melk Trupp',2),
(NULL, 'Tatortreiniger',2),
(NULL, 'TG Gaming',2),
(NULL, 'Without a Trace',2),
(NULL, 'Fysikbasserne',3),
(NULL, 'Helion',3),
(NULL, 'Twix',3),
(NULL, 'Unethical',3),
(NULL, 'Advance',3),
(NULL, 'Arctic Avengers',3),
(NULL, 'E V O L U T I O N',3),
(NULL, 'FOR THE ALLÎANCE',3),
(NULL, 'Insanity',3),
(NULL, 'Integrity',3),
(NULL, 'Oderant',3),
(NULL, 'P G',3),
(NULL, 'PMA',3),
(NULL, 'Revoke',3),
(NULL, 'stay hydrated',3),
(NULL, 'Sum optime',3),
(NULL, 'Team Sweden',3),
(NULL, 'Two Ghouls One Cup',3),
(NULL, 'Vous ne passerez pas',3),
(NULL, 'Øgma Tuatha',3),
(NULL, 'Адская Орда',3),
(NULL, 'Селфлесс',3),
(NULL, 'Чёрный Лотос',3),
(NULL, 'Crown',3),
(NULL, 'Distopia',3),
(NULL, 'FatSharkYes',3),
(NULL, 'Feed',3),
(NULL, 'Myst',3),
(NULL, 'Slack',3),
(NULL, 'Team Fight',3),
(NULL, 'The Haunted',3),
(NULL, 'Unicornz',3),
(NULL, 'В КОЛХОЗ ЗА ПЕТУХАМИ',3),
(NULL, 'THE MOVE',3),
(NULL, 'SSEN',3),
(NULL, 'Mørdor',3),
(NULL, 'one lesson per day',3),
(NULL, 'ddosed',3),
(NULL, 'hey im mvp',3),
(NULL, 'Still On Sargeras',3),
(NULL, 'ddosedx',3),
(NULL, 'Cyber Athletes',3),
(NULL, 'Gnomeland Security',3),
(NULL, 'ad hoc',3),
(NULL, 'slash spit',3),
(NULL, 'Suppy',3),
(NULL, 'Crimson Dragon',3),
(NULL, 'The Syndicate',3),
(NULL, 'Blur',3),
(NULL, 'tEh mOve',3),
(NULL, 'Cherry Pink',3),
(NULL, 'Honestly',3),
(NULL, 'Disney World',3),
(NULL, 'poptart corndoG',3),
(NULL, 'See Again Solitary',3),
(NULL, 'Infinity',3),
(NULL, 'BIG DAM',3),
(NULL, 'Ethical',3),
(NULL, 'BloodBoùnd',3),
(NULL, 'Show Me How',3),
(NULL, 'dog squad',3),
(NULL, 'Zandalari Bobsled Team',3),
(NULL, 'Goons Goonies',3),
(NULL, 'Legacy of the Alliance',3),
(NULL, 'Spiral Out',3),
(NULL, 'Melt',3),
(NULL, 'Last Attempt',3),
(NULL, 'Nolifer',3),
(NULL, 'RBG Hero',5),
(NULL, 'Medium',5),
(NULL, 'Nascent',5),
(NULL, 'M E R C I L E S S',5),
(NULL, 'Team Thougs',5),
(NULL, 'Verdict',5),
(NULL, 'CMG',5),
(NULL, 'Dishonorable Kill',5),
(NULL, 'Knights Who Say Yee',5),
(NULL, 'Restricted',5),
(NULL, 'Vile',5),
(NULL, 'Nemesis',5),
(NULL, 'Oasis',5),
(NULL, 'The Depraved',5),
(NULL, 'didnt ask',5),
(NULL, 'Epic Gamers',5),
(NULL, 'Essence',5),
(NULL, 'i love slicedbaka',5),
(NULL, 'Lights Oath',5),
(NULL, 'M Y T H I C C',5),
(NULL, 'Major Pain',5),
(NULL, 'Dads Against Vaping',5),
(NULL, 'No Skill',5),
(NULL, 'The Degenerates',5),
(NULL,'Boralus Yacht Club',5),
(NULL, 'Censored',5),
(NULL, 'Defenestrate',5),
(NULL, 'HATE DIVISION',5),
(NULL, 'hi',5),
(NULL, 'Ironsworn Regiment',5),
(NULL, 'is kinda like god',5),
(NULL, 'Temerity',5),
(NULL, 'The Pantheon NB',5),
(NULL, 'Vision',5),
(NULL, 'Baddies',5),
(NULL, 'Complexity Limit',5),
(NULL, 'Dark Clan of Fenris',5),
(NULL, 'Elite Horde',5),
(NULL, 'Makin a Bagel',5),
(NULL, 'Nimue',5),
(NULL, 'Ran Thru',5),
(NULL, 'Sin',5),
(NULL, 'VØDKA SØCIETY',5),
(NULL, 'Wizards and Monkeys',5),
(NULL, 'Is cute AF',5),
(NULL, 'Reckless Ambition',5),
(NULL, 'Solidarity Gaming',5),
(NULL, 'Spike Flail',5),
(NULL, 'Vexation',5),
(NULL, 'Hungry Wolves',5),
(NULL, 'Peel Team Six',5),
(NULL, 'Polaris',5),
(NULL, 'rest easy criter',5),
(NULL, 'Scripted',5),
(NULL, 'TAG',5),
(NULL, 'toXique',5),
(NULL, 'who are you talkin to',5),
(NULL, 'CRvillains',5),
(NULL, 'Decapodian',5),
(NULL, 'Fierce',5),
(NULL, 'Glad to see you',5),
(NULL, 'Impression',5),
(NULL, 'Nerd Rage',5),
(NULL, 'The Art of War',5),
(NULL, 'Wisdom',5),
(NULL, 'Against',2),
(NULL, 'Dot Run Profit',2),
(NULL, 'Fluffy Doods of Doom',2),
(NULL, 'Dot Pillar Profit',2),
(NULL, 'Team GG',2),
(NULL, 'Paizuri',2),
(NULL, 'Plz i need',2),
(NULL, 'shadow resist last week',2),
(NULL, 'shen diao xia lv',2),
(NULL, 'Speechless',2),
(NULL, 'Pandaninja Team',2),
(NULL, 'Kettes Ninja',2),
(NULL, 'PROXIMO',2),
(NULL, 'System Down',2),
(NULL, 'Hakuna matata',2),
(NULL, 'Freshly Baked',2),
(NULL, 'Abandon All Hope',2),
(NULL, 'GIEF UR POINTS PLX',2),
(NULL, 'Schobbejakken',2),
(NULL, 'Our team got deleted',2),
(NULL, 'Chocolate fingers',2),
(NULL, 'Wet Dreams',2),
(NULL, 'Vissnar er skit',2),
(NULL, 'Holla Fo Da Top Dolla',2),
(NULL, 'WTS Taran Icebreaker',2),
(NULL, 'Copenhagen eSports',2),
(NULL, 'SWE HORDE',2),
(NULL, 'I Touch Myself',2),
(NULL, 'Kines Jaegarna',2),
(NULL, 'Greek SOUVLAKI',2),
(NULL, 'Halinallet',2),
(NULL, 'TELLME WHEN THEY TRINKE',2),
(NULL, 'Team Obie',2),
(NULL, 'weh',2),
(NULL, 'Coconat Crew',2),
(NULL, 'DISPEL DUXE',2),
(NULL, 'Aftermath of GeekBoys',2),
(NULL, 'RockStarz',2),
(NULL, 'Triple Penetration',2),
(NULL, 'Abandoned hope',2),
(NULL, 'Againandagain',2),
(NULL, 'WTFGON',2),
(NULL, 'Chill',2),
(NULL, 'SUPERPVPPOWER',2),
(NULL, 'Funky ShEt',2),
(NULL, 'Cyclone it and Run',2),
(NULL, 'Mante and Alvi',2),
(NULL, 'Toku was off',2),
(NULL, 'BOOMHEADSHOT',2),
(NULL, 'Beer',2),
(NULL, 'Will you marry Me',2),
(NULL, 'Razer was a piece of St',2),
(NULL, 'More Dots',2),
(NULL, 'SuirotkiV',2),
(NULL, 'Celguar and Mostlikely',2),
(NULL, 'You got PWNed',2),
(NULL, 'Lido and Nonuse',2),
(NULL, 'I Am Your Father',2),
(NULL, 'TO XRYSO KOUFETO',2),
(NULL, 'FourKings',2),
(NULL, 'Dont hate the player',2),
(NULL, 'LF akashis replacement',2),
(NULL, 'Found Your Cookies',2),
(NULL, 'manglecritTIOtysen',2),
(NULL, 'For sale',2),
(NULL, 'Pirates',2),
(NULL, 'råttakuninkaat',2),
(NULL, 'DotaAPgogo',2),
(NULL, 'Has gone offline',2),
(NULL, 'Hide your Cookies',2),
(NULL, 'Player Hater Foundation',2),
(NULL, 'Something new',2),
(NULL, 'asdklfjkläasdhjkla',2),
(NULL, 'Ignorance is Bliss',2),
(NULL, 'Spellbook OPEN',2),
(NULL, 'BIG SMITING MACHINE',2),
(NULL, 'The Five Musketeers',2),
(NULL, 'Proximity',2),
(NULL, 'Artefakt',2),
(NULL, 'Devastation',2),
(NULL, 'Spawn more Overlords',2),
(NULL, 'We only log on for arena',2),
(NULL, 'Come Honour Face',2),
(NULL, 'High Caliberr',2),
(NULL, 'Wildhammer',2),
(NULL, 'We dont like Arena',2),
(NULL, 'No mercy for the noobs',2),
(NULL, 'we loose because of exor',2),
(NULL, 'Hit Me Hard',2),
(NULL, 'Variksen Orjat',2),
(NULL, 'Jumalauta',2),
(NULL, 'Baqa lack skills',2),
(NULL, 'The Crackheads',2),
(NULL, 'Me Smash You',2),
(NULL, 'Over the Top',2),
(NULL, 'We like cookies',2),
(NULL, 'Devil wears SRada',2),
(NULL, 'Healing Misery',2),
(NULL, 'Just gear',2),
(NULL, 'Mystical Is Fat Dorf IRL',2),
(NULL, 'DISPELL ME PLZ',2),
(NULL, 'Death Note',2),
(NULL, 'Wicked Grin',2),
(NULL, 'Analnie Oduvanchiki',2),
(NULL, 'eru bränd lr',2),
(NULL, 'we lose coz schade sux',2),
(NULL, 'forte gaming',2),
(NULL, 'Blitzkrieg Platoon',2),
(NULL, 'CC Inc',2),
(NULL, 'Razerium',2),
(NULL, 'Crusty Farmers',2),
(NULL, 'Unrated',2),
(NULL, 'jag grindar för guld',2),
(NULL, 'Razor',2),
(NULL, 'Sarahs Evil Minions',2),
(NULL, 'Brutal Team',2),
(NULL, 'apekatt',2),
(NULL, 'Diekmann',2),
(NULL, 'Balanced Combo',2),
(NULL, 'Team of Lolroots',2),
(NULL, 'Ajs is ubernoob',2),
(NULL, 'Snowy gryphon',2),
(NULL, 'steady hand',2),
(NULL, 'Imbanuke',2),
(NULL, 'Hello I like you',2),
(NULL, 'Pallokala',2),
(NULL, 'PuG And Pray',3),
(NULL, 'DoT BoTs',3),
(NULL, 'Italianstyle',3),
(NULL, 'Fear Inc',3),
(NULL, 'We survived Gnomeregan',3),
(NULL, 'Three Mighty Mice',3),
(NULL, 'Murlox',3),
(NULL, 'Poon',3),
(NULL, 'Manbearpig',3),
(NULL, 'Yea we lift',3),
(NULL, 'PuG KZ Fans',3),
(NULL, 'Abandoned',3),
(NULL, 'Rinse And Repeat',3),
(NULL, 'WHATS GOING ON',3),
(NULL, 'Chillside',3),
(NULL, 'SUPERPVEPOWER',3),
(NULL, 'Juicy Guys',3),
(NULL, 'Cyclone and Run',3),
(NULL, 'Check and Mate',3),
(NULL, 'CC to Death',3),
(NULL, 'two gimps and mighty pet',3),
(NULL, 'Boulderfist Geeks',3),
(NULL, 'Sap and Consecration',3),
(NULL, 'Rusty Robocop',3),
(NULL, 'More Dots Plx',3),
(NULL, 'kARVAKAMUT',3),
(NULL, 'Your face',3),
(NULL, 'You got Stoneformed',3),
(NULL, 'fluffy evil bunnies',3),
(NULL, 'watrox elemental iceblox',3),
(NULL, 'Serotonine',3),
(NULL, 'Imbalanced',3),
(NULL, 'inYaface',3),
(NULL, 'lol we liek pie',3),
(NULL, 'Pat Sharp Celebrity DJ',3),
(NULL, 'Eighty gold WTF',3),
(NULL, 'Righteous Rage',3),
(NULL, 'momma said knock you out',3),
(NULL, 'TeletabiTransformers',3),
(NULL, 'Team Murloc',3),
(NULL, 'GK',3),
(NULL, 'kayfour',3),
(NULL, 'we loose cos spraaty sux',3),
(NULL, 'Infected Infinity',3),
(NULL, 'Demogorgon sux',3),
(NULL, 'My mate sux',3),
(NULL, 'Set to Kill',3),
(NULL, 'Team China',3),
(NULL, 'schlag',3),
(NULL, 'klops',3),
(NULL, 'HAF A NAIS CUP O MANGEL',3),
(NULL, 'Mantrain of Love',3),
(NULL, 'The Light Embrace',3),
(NULL, 'Team Glasmastarn',3),
(NULL, 'Dwarf Wet Tshirt Team',3),
(NULL, 'Tur med Vädret INC',3),
(NULL, 'Dumb Dumber Dimtim',3),
(NULL, 'Büdösbunkók',3),
(NULL, 'ze germans are coming',3),
(NULL, 'XND',3),
(NULL, 'Hooked up by LFG chat',3),
(NULL, 'KaplA',3),
(NULL, 'The Perfect Storm',3),
(NULL, 'ashwjzrwtficantmove',3),
(NULL, 'Strawberry',3),
(NULL, 'Three Ladies',3),
(NULL, 'I Dont Know',3),
(NULL, 'Our warrior cant do dmg',3),
(NULL, 'Lockout',3),
(NULL, 'Scrubs',3),
(NULL, 'Tarmed',3),
(NULL, 'Knockout',3),
(NULL, 'Trollout',3),
(NULL, 'Midgets and Co',3),
(NULL, 'toy soldiers',3),
(NULL, 'Your Nightmare',3),
(NULL, 'lack of experience',3),
(NULL, 'socialbidrag',3),
(NULL, 'Sweep The Leg',3),
(NULL, 'YourMomIsAnEpicMount',3),
(NULL, 'Captain Birdseye',3),
(NULL, 'Wasted Talent',3),
(NULL, 'Hammer Time',3),
(NULL, 'Really Powerful PvP',3),
(NULL, 'TESTOVOIMAA',3),
(NULL, 'Reptile in my Pants',3),
(NULL, 'Insert Coin',3),
(NULL, 'Vixens',3),
(NULL, 'Keyboard Blackbelts',3),
(NULL, 'Giggity',3),
(NULL, 'Landoo',3),
(NULL, 'GG MAN',3),
(NULL, 'excrucio',3),
(NULL, 'Recklessness',3),
(NULL, 'envious',3),
(NULL, 'Mordbrenner',3),
(NULL, 'not my account',3),
(NULL, 'Wir ausm Märchenland',3),
(NULL, 'Erdbeerwochen',3),
(NULL, 'Vierundzwanzig sieben',3),
(NULL, 'PiDaBeLJueNDi',3),
(NULL, 'Target was friendly',3),
(NULL, 'Straight Outta Pjöngjang',3),
(NULL, 'Y not',3),
(NULL, 'Infamous',3),
(NULL, 'NullachtfünfzehneR',5),
(NULL, 'Dunkle Schar',5),
(NULL, 'Flex',5),
(NULL, 'Chîkara',5),
(NULL, 'because size does matter',5),
(NULL, 'wir ownen euch JETZT',5),
(NULL, 'three bathing beauties',5),
(NULL, 'Straight Outta Timbuktu',5),
(NULL, 'Keyboard Turnerrizor',5),
(NULL, 'dinosekz',5),
(NULL, 'kÁ',5),
(NULL, 'Boondock Pandas',5),
(NULL, 'perfect',5),
(NULL, 'Dracorex',5),
(NULL, 'Annihilation',5),
(NULL, 'X files',5),
(NULL, 'Kuschlig weich',5),
(NULL, 'Arcanum',5),
(NULL, 'fatalis drei',5),
(NULL, 'Psyms Team',5),
(NULL, 'Push it to the Límit',5),
(NULL, 'MassacreGamingDotCom',5),
(NULL, 'need equip',5),
(NULL, 'First Kill',5),
(NULL, 'Sand in der Vaseline',5),
(NULL, 'Panda',5),
(NULL, 'Eradication Instincts',5),
(NULL, 'eMiNeNCe',5),
(NULL, 'O M F G ICH ZERHACK DICH',5),
(NULL, 'foresighted',5),
(NULL, 'heavy petting zoo',5),
(NULL, 'Pew Pew Laser',5),
(NULL, 'OMFG ICH ZERHACK DICH II',5),
(NULL, 'Maustilicious',5),
(NULL, 'FAQ',5),
(NULL, 'Dreist',5),
(NULL, 'Höllenflämmchen',5),
(NULL, 'five mins no rush',5),
(NULL, 'Sarang',5),
(NULL, 'Die Wiederkäuer',5),
(NULL, 'Schäfchen reloaded',5),
(NULL, 'excellent',5),
(NULL, 'Abyza',5),
(NULL, 'n to the p',5),
(NULL, 'haRdcorE baSh',5),
(NULL, 'TeaM LoTTo',5),
(NULL, 'Shattered Hand says hi',5),
(NULL, 'Troll Cat',5),
(NULL, 'Hilgrim INC',5),
(NULL, 'Panda Assault',5),
(NULL, 'Enter Victory',5),
(NULL, 'Hung like a Cow',5),
(NULL, 'Sangis Cobras',5),
(NULL, 'Team Failure',5),
(NULL, 'Viva Pinatas',5),
(NULL, 'Blood Brothers',5),
(NULL, 'Swomp Was Here',5),
(NULL, 'ÆNima',5),
(NULL, 'Team Poison',5),
(NULL, 'WTB Flying Pink Elephant',5),
(NULL, 'Thiz is a mans world',5),
(NULL, 'Ri',5),
(NULL, 'Poison',5),
(NULL, 'BARE AND PLATE',5),
(NULL, 'Skuggelaget',5),
(NULL, 'Le Pinatas',5),
(NULL, 'Finish Him',5),
(NULL, 'Gentle Seduction',5),
(NULL, 'Warrior Mage Paladin',5),
(NULL, 'Haha',5),
(NULL, 'NewtypE',5),
(NULL, 'Mazinger Z',5),
(NULL, 'Triple Impact',5),
(NULL, 'Me lieK',5),
(NULL, 'beep beep i am jeep',5),
(NULL, 'Imprudent',5),
(NULL, 'Galaxy Angel Team',5),
(NULL, 'IceCrown',5),
(NULL, 'Nba',5),
(NULL, 'We fight for pie',5),
(NULL, 'OK',5),
(NULL, 'Randoms',5),
(NULL, 'Wanna Be',5),
(NULL, 'WANNA GO UBRS NVM AB LOL',5),
(NULL, 'Deadly n Stuff',5),
(NULL, 'Shadow Vulnerability',5),
(NULL, 'Occult',5),
(NULL, 'Crab People',5),
(NULL, 'ena xeri kai ena podi',5),
(NULL, 'OutPlayed',5),
(NULL, 'No Life',5),
(NULL, 'Shadows Edge',5),
(NULL, 'Durotar Fight Club',5),
(NULL, 'Warriors are easy',5),
(NULL, 'Shatter',5),
(NULL, 'Powerhouse',5),
(NULL, 'Higitus Figitus',5),
(NULL, 'RIP',5),
(NULL, 'TSoG',5),
(NULL, 'JUSTINS ENTOURAGE',5),
(NULL, 'Guess Who',5),
(NULL, 'Feeders Club',5),
(NULL, 'Crab Pupils',5),
(NULL, 'lol its a bird',5),
(NULL, 'Deaf In Texas',5),
(NULL, 'Millenium',5),
(NULL, 'Les Pores',5),
(NULL, 'No need War',5),
(NULL, 'Overall',5),
(NULL, 'WeLoseCozLweySux',5),
(NULL, 'Epik Boyz de Lumière',5),
(NULL, 'Himalaya',5),
(NULL, 'Take it deep RETURNZ',5),
(NULL, 'Gangrenaab',5),
(NULL, 'Millenium Stylz',5),
(NULL, 'Where is my umbrella',5),
(NULL, 'Esport LOL',5),
(NULL, 'HARDCORE UNITED',5),
(NULL, 'Korean Wannabe',5),
(NULL, 'Nétalïon',5),
(NULL, 'Mega Jaunes volume Deux',5),
(NULL, 'Impending Doom',5),
(NULL, 'Les Poulets Fringuants',5),
(NULL, 'Kool and teh Gank',5),
(NULL, 'Mille Margoulins',5),
(NULL, 'Naabz',5),
(NULL, 'Need du stuff plz',5),
(NULL, 'Typhoon',5),
(NULL, 'A new Begining',5),
(NULL, 'Est',5),
(NULL, 'Les Rois Mages',5),
(NULL, 'WeLooseCuzImoSux',5),
(NULL, 'WeLozCozShamSuX',5),
(NULL, 'WeLoseCuzNetherSux',5),
(NULL, 'eXecut Him',5),
(NULL, 'Økra est unstuff',5),
(NULL, 'WeLoseCauzNetherSux',5),
(NULL, 'WeLoseCozVixcisSux',5),
(NULL, 'RAT',5),
(NULL, 'a A a Arena',5),
(NULL, 'OMG',5),
(NULL, 'NoraJ ThX',5),
(NULL, 'Tendresse et calin',5),
(NULL, 'Laming is not a crime',5),
(NULL, 'Over',5),
(NULL, 'You love it',5),
(NULL, 'Naturiste Dance',5),
(NULL, 'Dead Breed',5),
(NULL, 'To lazy',5),
(NULL, 'CN',5),
(NULL, 'Burn Mana',5),
(NULL, 'A vendre',5),
(NULL, 'We Lose Cuz Kisame Sux',5),
(NULL, 'Pestis Atra',5),
(NULL, 'Un vs deux',5),
(NULL, 'Pwee Pwee BOUM',5),
(NULL, 'Gnomette Team',5),
(NULL, 'Croque plz',5),
(NULL, 'Sux Compagny',5),
(NULL, 'JESUS SAVE ME',5),
(NULL, 'anatheme',5),
(NULL, 'heal mon pet ffs',5),
(NULL, 'Bip bip',5),
(NULL, 'MbT',5),
(NULL, 'CYCLONECOPTER',5),
(NULL, 'Sargeras',5),
(NULL, 'Dots n Hots or something',5),
(NULL, 'This bear can eat you',5),
(NULL, 'Combination of Male love',5),
(NULL, 'Right in Two',5),
(NULL, 'Rends Wrath',5),
(NULL, 'Vita Brevis',5),
(NULL, 'Tysken Justus',5),
(NULL, 'Iso Kikkeli',5),
(NULL, 'imbas',5),
(NULL, 'Me love You',5),
(NULL, 'We love pie',5),
(NULL, 'F U',5),
(NULL, 'CRITICAL ERROR',5),
(NULL, 'Epica',5),
(NULL, 'V i X',5),
(NULL, 'Derka Derka Derka',5),
(NULL, 'Killalot',5),
(NULL, 'Flagstång',5),
(NULL, 'The beauty and the beast',5);
