DROP TABLE IF EXISTS `emotetextsound_dbc`;
CREATE TABLE `emotetextsound_dbc` (
  `Id` INT NOT NULL DEFAULT '0',
  `EmotesTextId` INT NOT NULL DEFAULT '0',
  `RaceId` INT NOT NULL DEFAULT '0',
  `SexId` INT NOT NULL DEFAULT '0',
  `SoundId` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`Id`) USING BTREE
) ENGINE=MYISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
