DROP TABLE IF EXISTS `charsections_dbc`;
CREATE TABLE `charsections_dbc` (
  `Id` INT NOT NULL DEFAULT '0',
  `Race` INT NOT NULL DEFAULT '0',
  `Gender` INT NOT NULL DEFAULT '0',
  `GenType` INT NOT NULL DEFAULT '0',
  `TexturePath1` VARCHAR(100) DEFAULT NULL,
  `TexturePath2` VARCHAR(100) DEFAULT NULL,
  `TexturePath3` VARCHAR(100) DEFAULT NULL,
  `Flags` INT NOT NULL DEFAULT '0',
  `Type` INT NOT NULL DEFAULT '0',
  `Color` INT NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`) USING BTREE
) ENGINE=MYISAM DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci ROW_FORMAT=DYNAMIC;
