DROP TABLE IF EXISTS `ai_playerbot_texts`;
CREATE TABLE IF NOT EXISTS `ai_playerbot_texts` (
  `id` smallint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL COMMENT 'name - used in strategies/code as filter',
  `text` varchar(1024) NOT NULL COMMENT 'text',
  `say_type` tinyint(3) NOT NULL DEFAULT '0' COMMENT '0 - say, 1 - yell',
  `reply_type` tinyint(3) NOT NULL DEFAULT '0' COMMENT 'if > 0 then can be filtered as a response to chat',
  `text_loc1` varchar(1024) NOT NULL,
  `text_loc2` varchar(1024) NOT NULL,
  `text_loc3` varchar(1024) NOT NULL,
  `text_loc4` varchar(1024) NOT NULL,
  `text_loc5` varchar(1024) NOT NULL,
  `text_loc6` varchar(1024) NOT NULL,
  `text_loc7` varchar(1024) NOT NULL,
  `text_loc8` varchar(1024) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=537 DEFAULT CHARSET=UTF8;

/*!40000 ALTER TABLE `ai_playerbot_texts` DISABLE KEYS */;
INSERT INTO `ai_playerbot_texts` (`id`, `name`, `text`, `say_type`, `reply_type`, `text_loc1`, `text_loc2`, `text_loc3`, `text_loc4`, `text_loc5`, `text_loc6`, `text_loc7`, `text_loc8`) VALUES
	(1, 'suggest_instance', 'Anyone wants %instance?',			0, 0, '', 'Quelqu\'un fait %instance ?', '', '', '', '', '', ''),
	(2, 'suggest_instance', 'Any groups for %instance?',		0, 0, '', 'Des groupes pour %instance ?', '', '', '', '', '', ''),
	(3, 'suggest_instance', 'Need help for %instance?',			0, 0, '', 'Besoin d\'aide pour %instance ?', '', '', '', '', '', ''),
	(4, 'suggest_instance', 'LFD: %instance.',					0, 0, '', 'Cherche à faire : %instance', '', '', '', '', '', ''),
	(5, 'suggest_instance', 'Anyone needs %role for %instance?',0, 0, '', 'Quelqu\'un a besoin de %role pour %instance ?', '', '', '', '', '', ''),
	(6, 'suggest_instance', 'Missing %role for %instance?',		0, 0, '', '%role manquant pour %instance ?', '', '', '', '', '', ''),
	(7, 'suggest_instance', 'Can be a %role for %instance.',	0, 0, '', '%role disponible pour %instance', '', '', '', '', '', ''),
	(8, 'suggest_instance', 'Need help with %instance?',		0, 0, '', 'Besoin d\'aide avec %instance ?', '', '', '', '', '', ''),
	(9, 'suggest_instance', 'Need %role help with %instance?',	0, 0, '', 'Besoin d\'aide %role avec %instance ?', '', '', '', '', '', ''),
	(10, 'suggest_instance', 'Anyone needs gear from %instance?',0, 0, '', 'Quelqu\'un a besoin d\'équipement de %instance ?', '', '', '', '', '', ''),
	(11, 'suggest_instance', 'A little grind in %instance?', 	0, 0, '', 'Un peu de grind dans %instance ?', '', '', '', '', '', ''),
	(12, 'suggest_instance', 'WTR %instance', 					0, 0, '', 'Cherche à rejoindre %instance', '', '', '', '', '', ''),
	(13, 'suggest_instance', 'Need help for %instance.', 		0, 0, '', 'Besoin d\'aide pour %instance', '', '', '', '', '', ''),
	(14, 'suggest_instance', 'Wanna run %instance.', 			0, 0, '', 'Je veux faire %instance', '', '', '', '', '', ''),
	(15, 'suggest_instance', '%role looks for %instance.', 		0, 0, '', '%role recherche %instance', '', '', '', '', '', ''),
	(16, 'suggest_instance', 'What about %instance?', 			0, 0, '', 'Et %instance ?', '', '', '', '', '', ''),
	(17, 'suggest_instance', 'Who wants to farm %instance?', 	0, 0, '', 'Qui veut exploiter %instance ?', '', '', '', '', '', ''),
	(18, 'suggest_instance', 'Go in %instance?', 				0, 0, '', 'Aller à %instance ?', '', '', '', '', '', ''),
	(19, 'suggest_instance', 'Looking for %instance.', 			0, 0, '', 'À la recherche de %instance', '', '', '', '', '', ''),
	(20, 'suggest_instance', 'Need help with %instance quests?', 0, 0, '', 'Besoin d\'aide pour les quêtes %instance ?', '', '', '', '', '', ''),
	(21, 'suggest_instance', 'Wanna quest in %instance.', 		0, 0, '', 'Je veux une quête dans %instance', '', '', '', '', '', ''),
	(22, 'suggest_instance', 'Anyone with quests in %instance?', 0, 0, '', 'Quelqu\'un a des quêtes dans %instance ?', '', '', '', '', '', ''),
	(23, 'suggest_instance', 'Could help with quests in %instance.', 0, 0, '', 'Peux aider pour les quêtes dans %instance', '', '', '', '', '', ''),
	(24, 'suggest_instance', '%role: any place in group for %instance?', 0, 0, '', '%role : n\'importe quel rôle dans le groupe pour %instance ?', '', '', '', '', '', ''),
	(25, 'suggest_instance', 'Does anybody still run %instance this days?', 0, 0, '', 'Est-ce que quelqu\'un fait encore %instance ces jours-ci ?', '', '', '', '', '', ''),
	(26, 'suggest_instance', '%instance: anyone wants to take a %role?', 0, 0, '', '%instance : quelqu\'un veut prendre un %role ?', '', '', '', '', '', ''),
	(27, 'suggest_instance', 'Is there any point being %role in %instance?', 0, 0, '', 'Y a-t-il un intérêt à être %role dans %instance ?', '', '', '', '', '', ''),
	(28, 'suggest_instance', 'It is really worth to go to %instance?', 0, 0, '', 'Cela vaut-il vraiment la peine d\'aller dans %instance ?', '', '', '', '', '', ''),
	(29, 'suggest_instance', 'Anybody needs more people for %instance?', 0, 0, '', 'Quelqu\'un a besoin de plus de personnes pour %instance ?', '', '', '', '', '', ''),
	(30, 'suggest_instance', '%instance bosses drop good gear. Wanna run?', 0, 0, '', 'Les boss %instance drop du bon équipement. Tu veux nous rejoindre ?', '', '', '', '', '', ''),
	(31, 'suggest_instance', 'What about %instance?',			0, 0, '', 'Et %instance ?', '', '', '', '', '', ''),
	(32, 'suggest_instance', 'Anybody needs %role?', 			0, 0, '', 'Quelqu\'un a besoin de %role ?', '', '', '', '', '', ''),
	(33, 'suggest_instance', 'Anyone needs %role?', 			0, 0, '', 'Quelqu\'un a besoin de %role ?', '', '', '', '', '', ''),
	(34, 'suggest_instance', 'Who wants %instance?', 			0, 0, '', 'Qui veut %instance ?', '', '', '', '', '', ''),
	(35, 'suggest_instance', 'Can anybody summon me at %instance?', 0, 0, '', 'Quelqu\'un peut-il me TP à %instance ?', '', '', '', '', '', ''),
	(36, 'suggest_instance', 'Meet me in %instance', 			0, 0, '', 'Rencontrez-moi dans %instance', '', '', '', '', '', ''),
	(37, 'suggest_instance', 'Wanna quick %instance run', 		0, 0, '', 'Je veux faire rapidement %instance', '', '', '', '', '', ''),
	(38, 'suggest_instance', 'Wanna full %instance run', 		0, 0, '', 'Je veux faire %instance complètement', '', '', '', '', '', ''),
	(39, 'suggest_instance', 'How many times were you in %instance?', 0, 0, '', 'Combien de fois avez-vous été dans %instance ?', '', '', '', '', '', ''),
	(40, 'suggest_instance', 'Another %instance run?', 			0, 0, '', 'Une autre exécution de %instance ?', '', '', '', '', '', ''),
	(41, 'suggest_instance', 'Wiped in %instance? Take me instead!', 0, 0, '', 'Effacé dans %instance ? Prends-moi plutôt !', '', '', '', '', '', ''),
	(42, 'suggest_instance', 'Take me in %instance please.', 	0, 0, '', 'Prenez-moi dans %instance s\'il vous plaît.', '', '', '', '', '', ''),
	(43, 'suggest_instance', 'Quick %instance run?', 			0, 0, '', 'Faire rapidement %instance ?', '', '', '', '', '', ''),
	(44, 'suggest_instance', 'Full %instance run?', 			0, 0, '', 'Clean complet dans %instance ?', '', '', '', '', '', ''),
	(45, 'suggest_instance', 'Who can take %role to %instance?', 0, 0, '', 'Qui peut prendre %role à %instance ?', '', '', '', '', '', ''),
	(46, 'suggest_quest', 'Need help with %quest?', 			0, 0, '', 'Besoin d\'aide avec %quest ?', '', '', '', '', '', ''),
	(47, 'suggest_quest', 'Anyone wants to share %quest?', 		0, 0, '', 'Quelqu\'un veut partager %quest ?', '', '', '', '', '', ''),
	(48, 'suggest_quest', 'Anyone doing %quest?', 				0, 0, '', 'Quelqu\'un fait %quest ?', '', '', '', '', '', ''),
	(49, 'suggest_quest', 'Wanna do %quest.', 					0, 0, '', 'Je veux faire %quest', '', '', '', '', '', ''),
	(50, 'suggest_trade', 'Anyone to farm %category?', 			0, 0, '', 'Quelqu\'un pour farm %category ?', '', '', '', '', '', ''),
	(51, 'suggest_trade', 'Looking for help farming %category.', 0, 0, '', 'Vous cherchez de l\'aide pour farmer %category', '', '', '', '', '', ''),
	(52, 'suggest_trade', 'Damn %category are so expensive!', 	0, 0, '', 'Putain %category sont si chers!', '', '', '', '', '', ''),
	(53, 'suggest_trade', 'Wanna %category.', 					0, 0, '', 'Je veux %category', '', '', '', '', '', ''),
	(54, 'suggest_trade', 'Need help with %category.', 			0, 0, '', 'Besoin d\'aide avec %category', '', '', '', '', '', ''),
	(55, 'suggest_trade', 'WTB %category.', 					0, 0, '', 'Cherche à acheter %category', '', '', '', '', '', ''),
	(56, 'suggest_trade', 'Anyone interested in %category?', 	0, 0, '', 'Quiconque est intéressé par %category?', '', '', '', '', '', ''),
	(57, 'suggest_trade', 'WTS %category.', 					0, 0, '', 'Cherche à vendre %category', '', '', '', '', '', ''),
	(58, 'suggest_trade', 'I am selling %category cheaper than AH.', 0, 0, '', 'Je vends %category moins cher que l\'hôtel des ventes.', '', '', '', '', '', ''),
	(59, 'suggest_trade', 'Who wants to farm %category?', 		0, 0, '', 'Qui veut farmer %category ?', '', '', '', '', '', ''),
	(60, 'suggest_trade', 'Wanna farm %category.', 				0, 0, '', 'Je veux farmer %category', '', '', '', '', '', ''),
	(61, 'suggest_trade', 'Looking for party after %category.', 0, 0, '', 'Recherche de partie après %category', '', '', '', '', '', ''),
	(62, 'suggest_trade', 'Any %category are appreciated.', 	0, 0, '', 'Toute %category est appréciée.', '', '', '', '', '', ''),
	(63, 'suggest_trade', 'Buying anything of %category.', 		0, 0, '', 'Acheter quoi que ce soit de %category', '', '', '', '', '', ''),
	(64, 'suggest_trade', 'Wow, anybody is farming %category!', 0, 0, '', 'Wow, quelqu\'un farm %category !', '', '', '', '', '', ''),
	(65, 'suggest_trade', '%category are selling mad in the AH.', 0, 0, '', '%category se vendent follement dans l\'hôtel des ventes.', '', '', '', '', '', ''),
	(66, 'suggest_trade', 'AH is hot for %category.', 			0, 0, '', 'Hôtel des ventes est chaud pour %category', '', '', '', '', '', ''),
	(67, 'suggest_trade', '%category are on the market.', 		0, 0, '', '%category sont sur le marché.', '', '', '', '', '', ''),
	(68, 'suggest_trade', 'Wanna trade some %category.', 		0, 0, '', 'Je veux échanger une %category', '', '', '', '', '', ''),
	(69, 'suggest_trade', 'Need more %category.', 				0, 0, '', 'Besoin de plus de %category', '', '', '', '', '', ''),
	(70, 'suggest_trade', 'Anybody can spare some %category?', 	0, 0, '', 'Quelqu\'un peut-il épargner une %category ?', '', '', '', '', '', ''),
	(71, 'suggest_trade', 'Who wants %category?', 				0, 0, '', 'Qui veut %category ?', '', '', '', '', '', ''),
	(72, 'suggest_trade', 'Some %category please?', 			0, 0, '', 'Une %category s\'il vous plaît ?', '', '', '', '', '', ''),
	(73, 'suggest_trade', 'I should have got skill for %category.', 0, 0, '', 'J\'aurais dû avoir une compétence pour %category', '', '', '', '', '', ''),
	(74, 'suggest_trade', 'I am dying for %category.', 			0, 0, '', 'Je meurs d\'envie pour %category', '', '', '', '', '', ''),
	(75, 'suggest_trade', 'People are killing for %category.', 	0, 0, '', 'Les gens tuent pour %category', '', '', '', '', '', ''),
	(76, 'suggest_trade', '%category is a great bargain!', 		0, 0, '', '%category est une bonne affaire!', '', '', '', '', '', ''),
	(77, 'suggest_trade', 'Everybody is mad for %category!', 	0, 0, '', 'Tout le monde est fou de %category !', '', '', '', '', '', ''),
	(78, 'suggest_trade', 'Where is the best place to farm for %category?', 0, 0, '', 'Quel est le meilleur endroit pour farmer pour %category ?', '', '', '', '', '', ''),
	(79, 'suggest_trade', 'I am all set for %category.', 		0, 0, '', 'Je suis prêt pour %category', '', '', '', '', '', ''),
	(80, 'suggest_trade', 'Is it good to sell %category?', 		0, 0, '', 'Est-il bon de vendre %category ?', '', '', '', '', '', ''),
	(81, 'suggest_trade', 'I\'d probably keep all my %category with me.', 0, 0, '', 'Je garderais probablement toute ma %category avec moi.', '', '', '', '', '', ''),
	(82, 'suggest_trade', 'Need group? Maybe to farm some %category?', 0, 0, '', 'Besoin de groupe ? Peut-être pour farmer une certaine %category ?', '', '', '', '', '', ''),
	(83, 'suggest_trade', 'I am still thinking about %category.', 0, 0, '', 'Je pense toujours à %category', '', '', '', '', '', ''),
	(84, 'suggest_trade', 'I heard about %category already, but my pockets are empty.', 0, 0, '', 'J\'ai déjà entendu parler de %category , mais mes poches sont vides.', '', '', '', '', '', ''),
	(85, 'suggest_trade', 'LFG for %category', 					0, 0, '', 'Cherche un groupe pour %category', '', '', '', '', '', ''),
	(86, 'suggest_trade', 'Would selling %category make me rich?', 0, 0, '', 'Vendre %category me rendrait-il riche?', '', '', '', '', '', ''),
	(87, 'suggest_trade', 'OK. I an farming %category tomorrow.', 0, 0, '', 'D\'ACCORD. Je farm %category demain.', '', '', '', '', '', ''),
	(88, 'suggest_trade', 'Everyone is talking about %category.', 0, 0, '', 'Tout le monde parle de %category', '', '', '', '', '', ''),
	(89, 'suggest_trade', 'I saw at least ten people farming for %category.', 0, 0, '', 'J\'ai vu au moins dix personnes farmer pour %category', '', '', '', '', '', ''),
	(90, 'suggest_trade', 'I sold all my %category yesterday. I am completely broke!', 0, 0, '', 'J\'ai vendu tout mon %category hier. Je suis complètement fauché!', '', '', '', '', '', ''),
	(91, 'suggest_trade', 'Wanna join a guild farming for %category.', 0, 0, '', 'Je veux rejoindre une guilde farmant pour %category', '', '', '', '', '', ''),
	(92, 'suggest_faction', 'Anyone farming %faction rep?', 0, 0, '', 'Quelqu\'un farm la réput de %faction ?', '', '', '', '', '', ''),
	(93, 'suggest_faction', 'Anyone help with %faction?', 0, 0, '', 'Quelqu\'un aide-t-il %faction ?', '', '', '', '', '', ''),
	(94, 'suggest_faction', 'Wanna quest for %faction.', 0, 0, '', 'Je veux quêter %faction', '', '', '', '', '', ''),
	(95, 'suggest_faction', '%faction is the best.', 0, 0, '', '%faction est la meilleure.', '', '', '', '', '', ''),
	(96, 'suggest_faction', 'Need just a bit to be %level with %faction.', 0, 0, '', 'J\'ai besoin d\'un peu pour être au %level avec %faction', '', '', '', '', '', ''),
	(97, 'suggest_faction', 'Anyone got %level with %faction?', 0, 0, '', 'Quelqu\'un a-t-il %level avec %faction ?', '', '', '', '', '', ''),
	(98, 'suggest_faction', 'Who wants to be %level with %faction?', 0, 0, '', 'Qui veut être au %level avec %faction ?', '', '', '', '', '', ''),
	(99, 'suggest_faction', 'I\'ll never be %level with %faction.', 0, 0, '', 'Je ne serai jamais au %level avec %faction', '', '', '', '', '', ''),
	(100, 'suggest_faction', 'Someone missing %faction rep?', 0, 0, '', 'Quelqu\'un manque de reput de %faction ?', '', '', '', '', '', ''),
	(101, 'suggest_faction', 'Could help farming %faction rep.', 0, 0, '', 'Pourrait aider à farmer réput de %faction', '', '', '', '', '', ''),
	(102, 'suggest_faction', 'The more rep the better. Especially with %faction.', 0, 0, '', 'Plus il y a de réput, mieux c\'est. Surtout avec %faction', '', '', '', '', '', ''),
	(103, 'suggest_faction', '%faction: need %rndK for %level.', 0, 0, '', '%faction: besoin %rndK pour %level.', '', '', '', '', '', ''),
	(104, 'suggest_faction', 'Who can share %faction quests?', 0, 0, '', 'Qui peut partager les quêtes de %faction ?', '', '', '', '', '', ''),
	(105, 'suggest_faction', 'Any dungeons for %faction?', 0, 0, '', 'Des donjons pour %faction ?', '', '', '', '', '', ''),
	(106, 'suggest_faction', 'Wanna do %faction rep grind.', 0, 0, '', 'Je veux faire monter ma réput %faction', '', '', '', '', '', ''),
	(107, 'suggest_faction', 'Let\'s farm %faction rep!', 0, 0, '', 'Farmons la réput %faction !', '', '', '', '', '', ''),
	(108, 'suggest_faction', 'Farming for %faction rep.', 0, 0, '', 'Farmons pour la réput %faction', '', '', '', '', '', ''),
	(109, 'suggest_faction', 'Wanna farm for %faction.', 0, 0, '', 'Je veux farmer pour %faction', '', '', '', '', '', ''),
	(110, 'suggest_faction', 'Need help with %faction.', 0, 0, '', 'Besoin d\'aide avec %faction', '', '', '', '', '', ''),
	(111, 'suggest_faction', 'Is %faction sells something useful?', 0, 0, '', 'Est-ce que %faction vend quelque chose d\'utile ?', '', '', '', '', '', ''),
	(112, 'suggest_faction', 'Are there %faction vendors?', 0, 0, '', 'Y a-t-il des vendeurs %faction ?', '', '', '', '', '', ''),
	(113, 'suggest_faction', 'Who farms %faction?', 0, 0, '', 'Qui farm %faction ?', '', '', '', '', '', ''),
	(114, 'suggest_faction', 'Which is the best way to farm %faction?', 0, 0, '', 'Quelle est la meilleure façon de farmer %faction ?', '', '', '', '', '', ''),
	(115, 'suggest_faction', 'I hate %faction rep grind.', 0, 0, '', 'Je déteste le travail de %faction rep.', '', '', '', '', '', ''),
	(116, 'suggest_faction', 'I am so tired of %faction.', 0, 0, '', 'Je suis tellement fatigué de %faction', '', '', '', '', '', ''),
	(117, 'suggest_faction', 'Go for %faction?', 0, 0, '', 'Vous optez pour %faction ?', '', '', '', '', '', ''),
	(118, 'suggest_faction', 'Seems everyone is %level with %faction. Only me is late as usually.', 0, 0, '', 'On dirait que tout le monde est %level avec %faction Il n\'y a que moi qui suis en retard comme d\'habitude.', '', '', '', '', '', ''),
	(119, 'suggest_faction', 'LFG for %faction rep grind?', 0, 0, '', 'Cherche un groupe pour monter la réput des représentants de %faction ?', '', '', '', '', '', ''),
	(120, 'suggest_faction', 'Can anobody suggest a good spot for %faction rep grind?', 0, 0, '', 'Quelqu\'un peut-il suggérer un bon endroit pour monter les réput de %faction ?', '', '', '', '', '', ''),
	(121, 'suggest_faction', 'Would %faction rep benefit me?', 0, 0, '', 'Est-ce que la réput %faction me serait bénéfique ?', '', '', '', '', '', ''),
	(122, 'suggest_faction', 'Who would\'ve thought that %faction rep will be useful after all...', 0, 0, '', 'Qui aurait pensé que le représentant de %faction serait utile après tout...', '', '', '', '', '', ''),
	(123, 'suggest_faction', 'I wanna be exalted with all factions, starting with %faction.', 0, 0, '', 'Je veux être exalté avec toutes les factions, à commencer par %faction', '', '', '', '', '', ''),
	(124, 'suggest_faction', 'Is there any point to improve my rep with %faction?', 0, 0, '', 'Y a-t-il un intérêt à améliorer ma réputation avec %faction ?', '', '', '', '', '', ''),
	(125, 'suggest_faction', 'What is better for %faction? Quests or mob grinding?', 0, 0, '', 'Quoi de mieux pour %faction ? Quêtes ou mob pour XP?', '', '', '', '', '', ''),
	(126, 'suggest_faction', 'Will grind %faction rep for you. Just give me some gold.', 0, 0, '', 'Monte la reput de %faction pour vous. Donnez-moi juste de l\'or.', '', '', '', '', '', ''),
	(127, 'suggest_faction', 'I think grinding rep with %faction would take forever.', 0, 0, '', 'Je pense que monter la réput avec %faction prendrait une éternité.', '', '', '', '', '', ''),
	(128, 'suggest_faction', 'I am killing for %faction every day now but still far from %level.', 0, 0, '', 'Je tue pour %faction tous les jours maintenant, mais encore loin du %level', '', '', '', '', '', ''),
	(129, 'suggest_faction', 'At %level AH deposits will decrease, right?', 0, 0, '', 'Au %level, les dépôts hôtel des ventes diminueront, n\'est-ce pas?', '', '', '', '', '', ''),
	(130, 'suggest_faction', 'How many exalted reps do you have?', 0, 0, '', 'Combien de représentants exaltés avez-vous ?', '', '', '', '', '', ''),
	(131, 'suggest_faction', 'Who wants to be %level with %faction?', 0, 0, '', 'Qui veut être au %level avec %faction ?', '', '', '', '', '', ''),
	(132, 'suggest_faction', 'Damn. My guild did a good %faction grind yesterday without me.', 0, 0, '', 'Mince. Ma guilde a fait un bon travail de %faction hier sans moi.', '', '', '', '', '', ''),
	(133, 'suggest_faction', 'Nobody wants to help me because I am %level with %faction.', 0, 0, '', 'Personne ne veut m\'aider parce que je suis %level avec %faction', '', '', '', '', '', ''),
	(134, 'suggest_faction', 'Please stay away from %faction.', 0, 0, '', 'Veuillez rester à l\'écart de %faction', '', '', '', '', '', ''),
	(135, 'suggest_something', 'Wanna party in %zone.', 0, 0, '', 'Je veux faire la fête dans %zone.', '', '', '', '', '', 'Ищу группу в %zone.'),
	(136, 'suggest_something', 'Anyone is looking for %role?', 0, 0, '', 'Quelqu\'un cherche un %role ?', '', '', '', '', '', 'Кто-нибудь ищет %role?'),
	(137, 'suggest_something', '%role is looking for quild.', 0, 0, '', '%role recherche une guilde.', '', '', '', '', '', '%role ищу гильдию.'),
	(138, 'suggest_something', 'Looking for gold.', 0, 0, '', 'A la recherche de l\'or.', '', '', '', '', '', 'Дайте голды'),
	(139, 'suggest_something', '%role wants to join a good guild.', 0, 0, '', '%role veut rejoindre une bonne guilde.', '', '', '', '', '', '%role хочу в хорошую гильдию.'),
	(140, 'suggest_something', 'Need a friend.', 0, 0, '', 'Besoin d\'un ami.', '', '', '', '', '', 'Ищу друга.'),
	(141, 'suggest_something', 'Anyone feels alone?', 0, 0, '', 'Quelqu\'un se sent seul?', '', '', '', '', '', 'Кому-нибудь одиноко?'),
	(142, 'suggest_something', 'Boring...', 0, 0, '', 'Ennuyeux...', '', '', '', '', '', 'Скучно...'),
	(143, 'suggest_something', 'Who wants some?', 0, 0, '', 'Qui en veut?', '', '', '', '', '', 'Кому навалять?'),
	(144, 'suggest_something', 'Go get me!', 0, 0, '', 'Allez me chercher !', '', '', '', '', '', 'Поймайте меня!'),
	(145, 'suggest_something', 'Maybe a duel in %zone?', 0, 0, '', 'Peut-être un duel dans %zone ?', '', '', '', '', '', 'Кто на дуэль в %zone?'),
	(146, 'suggest_something', 'Anybody doing something?', 0, 0, '', 'Quelqu\'un fait quelque chose?', '', '', '', '', '', 'Кто чем занят?'),
	(147, 'suggest_something', '%zone: is anybody here?', 0, 0, '', '%zone : est-ce que quelqu\'un est là?', '', '', '', '', '', '%zone: есть кто нибудь?'),
	(148, 'suggest_something', '%zone: where is everyone?', 0, 0, '', '%zone : où est tout le monde?', '', '', '', '', '', '%zone: где все?'),
	(149, 'suggest_something', 'Looks like I am alone in %zone.', 0, 0, '', 'On dirait que je suis seul dans %zone', '', '', '', '', '', 'Похоже я один в %zone.'),
	(150, 'suggest_something', 'Meet me in %zone.', 0, 0, '', 'Retrouvez-moi dans %zone', '', '', '', '', '', 'Встретимся в %zone.'),
	(151, 'suggest_something', 'Let\'s quest in %zone!', 0, 0, '', 'Partons en quête dans %zone !', '', '', '', '', '', 'Давайте квестить в %zone!'),
	(152, 'suggest_something', '%zone is the best place to be!', 0, 0, '', '%zone est le meilleur endroit où être!', '', '', '', '', '', '%zone лучшее место!'),
	(153, 'suggest_something', 'Wanna go to %zone. Anybody with me?', 0, 0, '', 'Je veux aller à %zone Quelqu\'un avec moi?', '', '', '', '', '', 'Собираюсь в %zone. Кто со мной7'),
	(154, 'suggest_something', 'Who wants going to %zone?', 0, 0, '', 'Qui veut aller à %zone ?', '', '', '', '', '', 'Кто собирается в %zone?'),
	(155, 'suggest_something', 'I don\'t like %zone. Where to go?', 0, 0, '', 'Je n\'aime pas %zone Où aller?', '', '', '', '', '', 'Не нравится %zone. Куда идти?'),
	(156, 'suggest_something', 'Are there a good quests in %zone?', 0, 0, '', 'Y a-t-il de bonnes quêtes dans %zone ?', '', '', '', '', '', 'А в %zone есть хорошие квесты?'),
	(157, 'suggest_something', 'Where to go after %zone?', 0, 0, '', 'Où aller après %zone ?', '', '', '', '', '', 'Куда идти после %zone?'),
	(158, 'suggest_something', 'Who is in %zone?', 0, 0, '', 'Qui est dans %zone ?', '', '', '', '', '', 'Кто в %zone?'),
	(159, 'suggest_something', 'LFG in %zone.', 0, 0, '', 'Cherche un groupe dans %zone', '', '', '', '', '', 'ЛФГ %zone.'),
	(160, 'suggest_something', '%zone is the worst place to be.', 0, 0, '', '%zone est le pire endroit où être.', '', '', '', '', '', '%zone это худшее место.'),
	(161, 'suggest_something', 'Catch me in %zone!', 0, 0, '', 'Attrape-moi dans %zone !', '', '', '', '', '', 'Поймай меня в %zone!'),
	(162, 'suggest_something', 'Go for %zone!', 0, 0, '', 'Allez pour %zone !', '', '', '', '', '', 'Гоу в %zone!'),
	(163, 'suggest_something', 'Wanna quest in %zone', 0, 0, '', 'Je veux une quête dans %zone', '', '', '', '', '', 'Хочешь поделать квесты в %zone'),
	(164, 'suggest_something', 'Anyone has quests in %zone?', 0, 0, '', 'Quelqu\'un a des quêtes dans %zone ?', '', '', '', '', '', 'Есть у кого квесты в %zone?'),
	(165, 'suggest_something', 'Come here to %zone!', 0, 0, '', 'Venez ici à %zone !', '', '', '', '', '', 'Приходите сюда в %zone!'),
	(166, 'suggest_something', 'Seems there is no Horde in %zone', 0, 0, '', 'Il semble qu\'il n\'y ait pas de Horde dans %zone', '', '', '', '', '', '%zone Орды вроде нет.'),
	(167, 'suggest_something', 'Seems there is no Alliance in %zone', 0, 0, '', 'Il semble qu\'il n\'y ait pas d\'alliance dans %zone', '', '', '', '', '', '%zone Альянса вроде нет'),
	(168, 'suggest_something', 'I am really tired of %zone. Maybe go somewhere else?', 0, 0, '', 'Je suis vraiment fatigué de %zone Peut-être aller ailleurs?', '', '', '', '', '', 'В %zone устал уже, может в другое место пойдем?'),
	(169, 'suggest_sell', 'WTS %item for %gold.', 0, 0, '', 'Cherche à vendre %item pour %gold', '', '', '', '', '', ''),
	(170, 'suggest_sell', 'Who wants %item for %gold?', 0, 0, '', 'Qui veut %item pour %gold ?', '', '', '', '', '', ''),
	(171, 'suggest_sell', 'Anyone wants %item? Only %gold.', 0, 0, '', 'Quelqu\'un veut %item ? Seulement %gold', '', '', '', '', '', ''),
	(172, 'suggest_sell', 'Just %gold for %item!', 0, 0, '', 'Seulement %gold pour %item!', '', '', '', '', '', ''),
	(173, 'suggest_sell', 'Selling %item for %gold.', 0, 0, '', 'Vendre %item pour %gold', '', '', '', '', '', ''),
	(174, 'suggest_sell', '%item is yours just for %gold!', 0, 0, '', '%item est à vous juste pour %gold !', '', '', '', '', '', ''),
	(175, 'suggest_sell', 'Ridiculus price of %gold for %item!', 0, 0, '', 'Prix ridicule de %gold pour %item !', '', '', '', '', '', ''),
	(176, 'suggest_sell', 'Wanna sell %item for %gold.', 0, 0, '', 'Je veux vendre %item pour %gold', '', '', '', '', '', ''),
	(177, 'suggest_sell', 'Who needs %item? Only %gold.', 0, 0, '', 'Qui a besoin de %item ? Seulement %gold', '', '', '', '', '', ''),
	(178, 'suggest_sell', 'Anyone needs %item for %gold?', 0, 0, '', 'Quelqu\'un a besoin de %item pour %gold ?', '', '', '', '', '', ''),
	(179, 'suggest_sell', '%gold for %item. Less than AH!', 0, 0, '', '%gold pour %item. Moins que l\'hôtel des ventes!', '', '', '', '', '', ''),
	(180, 'suggest_sell', '%item is expensive, but I\'d sell it for %gold.', 0, 0, '', '%item est cher, mais je le vendrais pour %gold', '', '', '', '', '', ''),
	(181, 'suggest_sell', 'You\'ll never find %item cheaper than %gold!', 0, 0, '', 'Vous ne trouverez jamais %item moins cher que %gold !', '', '', '', '', '', ''),
	(182, 'suggest_sell', 'Need more than %item!', 0, 0, '', 'Besoin de plus de %item !', '', '', '', '', '', ''),
	(183, 'suggest_sell', 'I have %item and need more.', 0, 0, '', 'J\'ai %item et j\'en ai besoin de plus.', '', '', '', '', '', ''),
	(184, 'suggest_sell', 'Have %item. Who wants to buy for %gold?', 0, 0, '', 'Avoir %item. Qui veut acheter pour %gold ?', '', '', '', '', '', ''),
	(185, 'suggest_sell', 'Anyone WTB %item for %gold?', 0, 0, '', 'Quelqu\'un cherche à acheter %item pour %gold ?', '', '', '', '', '', ''),
	(186, 'suggest_sell', 'What about %item? For %gold.', 0, 0, '', 'Qu\'en est-il de %item ? Pour %gold', '', '', '', '', '', ''),
	(187, 'suggest_sell', 'Who said I am a bastard? %item for %gold is a good price.', 0, 0, '', 'Qui a dit que j\'étais un bâtard? %item pour %gold est un bon prix.', '', '', '', '', '', ''),
	(188, 'suggest_sell', 'I am selling %item? Just %gold.', 0, 0, '', 'Je vends %item ? Juste %gold', '', '', '', '', '', ''),
	(189, 'suggest_sell', 'LFG for farming. You can still buy %item I have for %gold.', 0, 0, '', 'Cherche un groupe pour farming. Vous pouvez toujours acheter %item que j\'ai pour %gold', '', '', '', '', '', ''),
	(190, 'suggest_sell', 'Sold almost everything today. Still have %item for %gold.', 0, 0, '', 'Vendu presque tout aujourd\'hui. Vous avez encore %item pour %gold', '', '', '', '', '', ''),
	(191, 'suggest_sell', 'What use for trade chat? Of course to sell %item for %gold.', 0, 0, '', 'A quoi sert le tchat commercial? Bien sûr pour vendre %item pour %gold', '', '', '', '', '', ''),
	(192, 'suggest_sell', 'Can anyone beat the price of %gold for %item?', 0, 0, '', 'Quelqu\'un peut-il battre le prix de %gold pour %item ?', '', '', '', '', '', ''),
	(193, 'suggest_sell', 'Wanna stop trade chat? Just buy %item? For %gold!', 0, 0, '', 'Vous voulez arrêter le chat commercial? Vous venez d\'acheter %item ? Pour %gold !', '', '', '', '', '', ''),
	(194, 'suggest_sell', 'Everybody spams in trade chat. Me too - %gold for %item!', 0, 0, '', 'Tout le monde spamme dans le chat commercial. Moi aussi - %gold pour %item !', '', '', '', '', '', ''),
	(195, 'suggest_sell', 'Is %item any use? Just selling it for %gold.', 0, 0, '', '%item est-il utile? Je le vends juste pour %gold', '', '', '', '', '', ''),
	(196, 'suggest_sell', 'I have %item ready to sell you for %gold.', 0, 0, '', 'J\'ai %item prêt à vous vendre pour %gold', '', '', '', '', '', ''),
	(197, 'suggest_sell', 'Did nothing yesterday but have got %item. Selling it for %gold.', 0, 0, '', 'Je n\'ai rien fait hier mais j\'ai %item Je le vends pour %gold', '', '', '', '', '', ''),
	(198, 'suggest_sell', 'Farmed yesterday and got %item. Anyone wtb for %gold?', 0, 0, '', 'Farmé hier et obtenu %item Quelqu\'un cherche à acheter pour %gold ?', '', '', '', '', '', ''),
	(199, 'suggest_sell', 'Bought %item yesterday. Anyone needs it for %gold?', 0, 0, '', 'Acheté %item hier. Quelqu\'un en a besoin pour %gold ?', '', '', '', '', '', ''),
	(200, 'suggest_sell', 'Who asked for %item? The price is the same - %gold.', 0, 0, '', 'Qui a demandé %item ? Le prix est le même - %gold', '', '', '', '', '', ''),
	(201, 'suggest_sell', 'I sill have %item. WTB for %gold?', 0, 0, '', 'J\'ai toujours %item. Cherche à acheter pour %gold ?', '', '', '', '', '', ''),
	(202, 'suggest_sell', 'I used to have more than %item. Now needs to sell it for %gold.', 0, 0, '', 'J\'avais plus de %item Il faut maintenant le vendre pour %gold', '', '', '', '', '', ''),
	(203, 'suggest_sell', 'I wish I have more than %item. You could buy it for %gold anyways.', 0, 0, '', 'J\'aimerais avoir plus de %item . Vous pouvez l\'acheter pour %gold de toute façon.', '', '', '', '', '', ''),
	(204, 'suggest_sell', 'What use for your gold? To buy my %item for %gold.', 0, 0, '', 'A quoi sert votre or ? Pour acheter mon %item pour %gold', '', '', '', '', '', ''),
	(205, 'suggest_sell', 'Please spare some gold for me. You can buy %item for %gold.', 0, 0, '', 'S\'il vous plaît, épargnez-moi de l\'or. Vous pouvez acheter %item pour %gold', '', '', '', '', '', ''),
	(206, 'suggest_sell', 'Is %gold is a good price for %item?', 0, 0, '', '%gold est-il un bon prix pour %item ?', '', '', '', '', '', ''),
	(207, 'suggest_sell', 'Just bought yesterday %items, but do not need it anymore. Anyone wants for %gold?', 0, 0, '', 'Je viens d\'acheter hier %items , mais je n\'en ai plus besoin. Quelqu\'un veut %gold ?', '', '', '', '', '', ''),
	(208, 'suggest_sell', 'I am going to post %item on the AH but you can buy it now cheaper just for %gold.', 0, 0, '', 'Je vais poster %item à l\'hôtel des ventes mais vous pouvez l\'acheter maintenant moins cher juste pour %gold', '', '', '', '', '', ''),
	(209, 'suggest_sell', 'Why the #!@ have I bought %item? Anyone needs it for %gold?', 0, 0, '', 'Pourquoi ai-je acheté le #!@ %item ? Quelqu\'un en a besoin pour %gold ?', '', '', '', '', '', ''),
	(210, 'reply', 'what was that %s?', 0, 0, '', 'c\'était quoi ce %s?', '', '', '', '', '', ''),
	(211, 'reply', 'not sure I understand %s?', 0, 0, '', 'pas sûr de comprendre %s?', '', '', '', '', '', ''),
	(212, 'reply', 'uh... no clue what yer talkin bout', 0, 0, '', 'euh... aucune idée de quoi tu parles', '', '', '', '', '', ''),
	(213, 'reply', 'you talkin to me %s?', 0, 0, '', 'tu me parles %s?', '', '', '', '', '', ''),
	(214, 'reply', 'whaaaa?', 0, 0, '', 'quoiaaa?', '', '', '', '', '', ''),
	(215, 'reply', 'huh?', 0, 0, '', 'hein?', '', '', '', '', '', ''),
	(216, 'reply', 'what?', 0, 0, '', 'Quoi?', '', '', '', '', '', ''),
	(217, 'reply', 'are you talking?', 0, 0, '', 'parles-tu?', '', '', '', '', '', ''),
	(218, 'reply', 'whatever dude', 0, 0, '', 'peu importe mec', '', '', '', '', '', ''),
	(219, 'reply', 'you lost me', 0, 0, '', 'tu m\'as perdu', '', '', '', '', '', ''),
	(220, 'reply', 'Bla bla bla...', 0, 0, '', 'Bla bla bla...', '', '', '', '', '', ''),
	(221, 'reply', 'What did you say, %s?', 0, 0, '', 'Qu\'as-tu dis, %s?', '', '', '', '', '', ''),
	(222, 'reply', 'Concentrate on the game, %s!', 0, 0, '', 'Concentres-toi sur le jeu, %s!', '', '', '', '', '', ''),
	(223, 'reply', 'Chatting with you %s is so great! I always wanted to meet you', 0, 0, '', 'Discuter avec vous %s est tellement génial! J\'ai toujours voulu te rencontrer', '', '', '', '', '', ''),
	(224, 'reply', 'These chat-messages are freaking me out! I feel like I know you all!', 0, 0, '', 'Ces messages du chat me font flipper! J\'ai l\'impression de vous connaître tous!', '', '', '', '', '', ''),
	(225, 'reply', 'YEAH RIGHT! HAHA SURE!!!', 0, 0, '', 'OUI EN EFFET! AHAH BIEN SÛR!!!', '', '', '', '', '', ''),
	(226, 'reply', 'I believe you!!!', 0, 0, '', 'Je te crois!!!', '', '', '', '', '', ''),
	(227, 'reply', 'OK, uhuh LOL', 0, 0, '', 'OK, euh LOL', '', '', '', '', '', ''),
	(228, 'reply', 'Why is everybody always saying the same things???', 0, 0, '', 'Pourquoi tout le monde dit toujours la même chose???', '', '', '', '', '', ''),
	(229, 'reply', 'Hey %s....oh nevermind!', 0, 0, '', 'Hé %s.... oh tant pis!', '', '', '', '', '', ''),
	(230, 'reply', 'What are you talking about %s', 0, 0, '', 'De quoi parlez-vous %s', '', '', '', '', '', ''),
	(231, 'reply', 'Who said that? I resemble that remark', 0, 0, '', 'Qui a dit ça? je ressemble à cette remarque', '', '', '', '', '', ''),
	(232, 'reply', 'hey %s i havent forgotten you', 0, 1, '', 'salut %s je ne t\'ai pas oublié', '', '', '', '', '', ''),
	(233, 'reply', 'you piss me off %s', 0, 1, '', 'tu me fais chier %s', '', '', '', '', '', ''),
	(234, 'reply', 'im gunna get you this time %s', 0, 1, '', 'je vais t\'avoir cette fois %s', '', '', '', '', '', ''),
	(235, 'reply', 'better watch your back %s', 0, 1, '', 'mieux vaut surveiller vos arrières %s', '', '', '', '', '', ''),
	(236, 'reply', 'i did not like last round so much', 0, 1, '', 'je n\'ai pas tellement aimé le dernier tour', '', '', '', '', '', ''),
	(237, 'reply', 'i sucked last round thanks to %s', 0, 1, '', 'j\'ai merdé le dernier tour grâce à %s', '', '', '', '', '', ''),
	(238, 'reply', 'prepare to die %s', 0, 1, '', 'préparez-vous à mourir %s', '', '', '', '', '', ''),
	(239, 'reply', 'dont appreciate you killin me %s', 0, 1, '', 'j\'apprécie pas que tu me tues %s', '', '', '', '', '', ''),
	(240, 'reply', '%s, i hate you', 0, 1, '', '%s, je te déteste', '', '', '', '', '', ''),
	(241, 'reply', 'grrrrrr, ill get you this time %s', 0, 1, '', 'grrrrrr, je vais t\'avoir cette fois %s', '', '', '', '', '', ''),
	(242, 'reply', 'well fuck you', 0, 1, '', 'eh bien va te faire foutre', '', '', '', '', '', ''),
	(243, 'reply', 'wtf', 0, 2, '', 'wtf', '', '', '', '', '', ''),
	(244, 'reply', 'wtf??', 0, 2, '', 'wtf??', '', '', '', '', '', ''),
	(245, 'reply', 'low life', 0, 2, '', 'faible durée de vie', '', '', '', '', '', ''),
	(246, 'reply', 'wth', 0, 2, '', 'wth', '', '', '', '', '', ''),
	(247, 'reply', 'sucked', 0, 2, '', 'Ça craint', '', '', '', '', '', ''),
	(248, 'reply', 'REMATCH!!! im taking him down', 0, 2, '', 'REMATCH!!! je le descends', '', '', '', '', '', ''),
	(249, 'reply', 'pathetic, i got killed by %s', 0, 2, '', 'pathétique, j\'ai été tué par %s', '', '', '', '', '', ''),
	(250, 'reply', 'hehe, i nailed %s?', 0, 3, '', 'hehe, j\'ai cloué %s?', '', '', '', '', '', ''),
	(251, 'reply', 'that was too easy, killin %s', 0, 3, '', 'c\'était trop facile, de tuer %s', '', '', '', '', '', ''),
	(252, 'reply', 'gotcha mofo', 0, 3, '', 'je t\'ai eu enfoiré', '', '', '', '', '', ''),
	(253, 'reply', 'ha ha', 0, 3, '', 'ha ha', '', '', '', '', '', ''),
	(254, 'reply', 'loser', 0, 3, '', 'loser', '', '', '', '', '', ''),
	(255, 'reply', 'i killed %s and yer all next dudes', 0, 3, '', 'j\'ai tué %s et vous tous les prochains mecs', '', '', '', '', '', ''),
	(256, 'reply', 'oh yeah i owned him', 0, 3, '', 'oh ouais je l\'ai possédé', '', '', '', '', '', ''),
	(257, 'reply', 'im a killin machine', 0, 3, '', 'je suis une machine à tuer', '', '', '', '', '', ''),
	(258, 'reply', '%s,  this reminds me of a Slayer song...all this bloodshed', 0, 3, '', '%s, ça me rappelle une chanson de Slayer... tout ce bain de sang', '', '', '', '', '', ''),
	(259, 'reply', 'sorry, %s. can we do the scene again?', 0, 3, '', 'désolé, %s. peut-on refaire la scène?', '', '', '', '', '', ''),
	(260, 'reply', 'so....how do you like being worm food %s???', 0, 3, '', 'alors... comment aimez-vous être de la nourriture pour vers %s???', '', '', '', '', '', ''),
	(261, 'reply', 'yer supposed to be dead, %s its part of the game!!!!!', 0, 3, '', 'tu es censé être mort, %s ça fait partie du jeu!!!!!', '', '', '', '', '', ''),
	(262, 'reply', 'sorry, %s. that looked as good as an Andy Worhol painting!', 0, 3, '', 'désolé, %s. ça avait l\'air aussi bien qu\'une peinture d\'Andy Warhol!', '', '', '', '', '', ''),
	(263, 'reply', '%s, ill use the rubber bullets next time !', 0, 3, '', '%s, j\'utiliserai pas les balles en caoutchouc la prochaine fois!', '', '', '', '', '', ''),
	(264, 'reply', 'whatsamatter, %s?? lose your head? hahaha gotta keep cool!!', 0, 3, '', 'qu\'importe, %s ?? tu perds la tête? hahaha faut rester cool!!', '', '', '', '', '', ''),
	(265, 'reply', 'i had to do it, %s. You understand. The Director said so!!', 0, 3, '', 'je devais le faire, %s. Tu comprends. Le directeur l\'a dit!!', '', '', '', '', '', ''),
	(266, 'reply', 'hey %s.......MUAHAHAHAHAHAHAHAHAHAHA', 0, 3, '', 'Salut %s.......MUAHAHAHAHAHAHAHAHAHAHA', '', '', '', '', '', ''),
	(267, 'reply', '%s, i enjoyed that one!! Lets play it again Sam', 0, 3, '', '%s, j\'ai adoré celui-là !! Jouons à nouveau Sam', '', '', '', '', '', ''),
	(268, 'reply', 'hey, %s! ju can start callin me scarface.. ju piece of CHIT!!!!', 0, 3, '', 'Hé, %s ! ju peut commencer à m\'appeler Scarface .. ju merde!!!!', '', '', '', '', '', ''),
	(269, 'reply', 'are you talking to me %s??', 0, 3, '', 'tu me parles %s ??', '', '', '', '', '', ''),
	(270, 'reply', '%s get it right this time, dont stand in front of my bullets.', 0, 3, '', '%s réussis cette fois, ne te tiens pas devant mes balles.', '', '', '', '', '', ''),
	(271, 'reply', '%s, what are you laying around for??? hehe', 0, 3, '', '%s, pourquoi traînes-tu??? hé hé', '', '', '', '', '', ''),
	(272, 'reply', 'hi %s', 0, 4, '', 'salut %s', '', '', '', '', '', ''),
	(273, 'reply', 'oh, hi %s', 0, 4, '', 'oh, salut %s', '', '', '', '', '', ''),
	(274, 'reply', 'wazzup %s!!!', 0, 4, '', 'Quoi de neuf %s!!!', '', '', '', '', '', ''),
	(275, 'reply', 'hi', 0, 4, '', 'salut', '', '', '', '', '', ''),
	(276, 'reply', 'wazzup', 0, 4, '', 'wazzup', '', '', '', '', '', ''),
	(277, 'reply', 'hello %s', 0, 4, '', 'bonjour %s', '', '', '', '', '', ''),
	(278, 'reply', 'hi %s, do i know you?', 0, 4, '', 'Salut %s, est-ce que je te connais ?', '', '', '', '', '', ''),
	(279, 'reply', 'hey %s', 0, 4, '', 'salut %s', '', '', '', '', '', ''),
	(280, 'reply', 'hai %s', 0, 4, '', 'ha %s', '', '', '', '', '', ''),
	(281, 'reply', 'wth', 0, 6, '', 'wth', '', '', '', '', '', ''),
	(282, 'reply', 'wtf', 0, 6, '', 'wtf', '', '', '', '', '', ''),
	(283, 'reply', 'this is bs', 0, 6, '', 'c\'est bs', '', '', '', '', '', ''),
	(284, 'reply', 'admin', 0, 6, '', 'admin', '', '', '', '', '', ''),
	(285, 'reply', 'hey %s quit abusing your admin', 0, 6, '', 'hé %s arrête d\'abuser de ton admin', '', '', '', '', '', ''),
	(286, 'reply', 'leave me alone admin!', 0, 6, '', 'laissez-moi tranquille admin!', '', '', '', '', '', ''),
	(287, 'reply', 'you suck admin', 0, 6, '', 'tu es nul admin', '', '', '', '', '', ''),
	(288, 'reply', 'thats my name, what you want %s', 0, 5, '', 'c\'est mon nom, qu\'est-ce que tu veux %s', '', '', '', '', '', ''),
	(289, 'reply', 'yes???', 0, 5, '', 'Oui???', '', '', '', '', '', ''),
	(290, 'reply', 'uh... what', 0, 5, '', 'euh ...quoi', '', '', '', '', '', ''),
	(291, 'reply', 'you talkin to me %s?', 0, 5, '', 'tu me parles %s ?', '', '', '', '', '', ''),
	(292, 'taunt', 'I have puppies under my armor!', 0, 0, '', 'J\'ai des chiots sous mon armure !', '', '', '', '', '', ''),
	(293, 'taunt', 'Bite me, <target>!', 0, 0, '', 'Mords moi, <target>!', '', '', '', '', '', ''),
	(294, 'taunt', 'Hey <target>! Guess what your mom said last night!', 0, 0, '', 'Hey <target>! Devine ce que ta mère a dit hier soir!', '', '', '', '', '', ''),
	(295, 'taunt', '<target>, you\'re so ugly you couldn\'t score in a monkey whorehouse with a bag of bananas!', 0, 0, '', '<target>, tu es si moche que tu ne pourrais pas marquer dans un bordel de singes avec un sac de bananes!', '', '', '', '', '', ''),
	(296, 'taunt', 'Shut up <target>, you\'ll never be the man your mother is!!', 0, 0, '', 'Tais-toi <target>, tu ne seras jamais l\'homme qu\'est ta mère!!', '', '', '', '', '', ''),
	(297, 'taunt', 'Your mother was a hampster and your father smelt of elderberries!!!!', 0, 0, '', 'Ta mère était un hamster et ton père sentait le sureau!!!!', '', '', '', '', '', ''),
	(298, 'taunt', 'I don\'t want to talk to you no more, you empty headed animal food trough wiper!!!', 0, 0, '', 'Je ne veux plus te parler, espèce d\'essuyeur d\'abreuvoirs pour animaux tête vide!!!', '', '', '', '', '', ''),
	(299, 'taunt', 'I fart in your general direction!!!', 0, 0, '', 'Je pète dans votre direction générale!!!', '', '', '', '', '', ''),
	(300, 'taunt', 'Go and boil your bottom, you son of a silly person!!!', 0, 0, '', 'Va te faire cuire le cul, fils d\'idiot!!!', '', '', '', '', '', ''),
	(301, 'taunt', 'What are you going to do <target>, bleed on me? HAVE AT YOU!', 0, 0, '', 'Qu\'est ce que tu vas faire <target>, saigner sur moi? A VOUS!', '', '', '', '', '', ''),
	(302, 'taunt', 'M-O-O-N! That spells aggro!', 0, 0, '', 'PUNAISE! Ce sort aggro!', '', '', '', '', '', ''),
	(303, 'taunt', 'You\'re about as useful as a one-legged man in an ass kicking contest.', 0, 0, '', 'Tu es à peu près aussi utile qu\'un homme unijambiste dans un concours de coups de pied au cul.', '', '', '', '', '', ''),
	(304, 'taunt', 'Hey <target>! Stop hitting on them, they\'re not your type. They aren\'t inflatable.', 0, 0, '', 'Hey <target>! Arrête de les draguer, ce n\'est pas ton genre. Ils ne sont pas gonflables.', '', '', '', '', '', ''),
	(305, 'taunt', '<target> you\'re so far outta your league, you\'re playing a different sport.', 0, 0, '', '<target> vous êtes tellement hors de votre ligue que vous pratiquez un sport différent.', '', '', '', '', '', ''),
	(306, 'taunt', 'You made a big mistake today <target>, you got out of bed.', 0, 0, '', 'Tu as fait une grosse erreur aujourd\'hui <target>, tu es sorti du lit.', '', '', '', '', '', ''),
	(307, 'taunt', 'I wanna try turning into a horse, but I need help. I\'ll be the front, you be yourself.', 0, 0, '', 'Je veux essayer de me transformer en cheval, mais j\'ai besoin d\'aide. Je serai devant, tu seras toi-même.', '', '', '', '', '', ''),
	(308, 'taunt', 'Can I borrow your face for a few days? My ass is going on holiday....', 0, 0, '', 'Puis-je emprunter votre visage pendant quelques jours? Mon cul part en vacances....', '', '', '', '', '', ''),
	(309, 'taunt', 'I\'d like to give you a going away present... First you do your part.', 0, 0, '', 'J\'aimerais vous offrir un cadeau de départ... D\'abord, donnes ta part.', '', '', '', '', '', ''),
	(310, 'taunt', 'Before you came along we were hungry, Now we\'re just fed up.', 0, 0, '', 'Avant que tu n\'arrives nous avions faim, maintenant nous en avons juste marre.', '', '', '', '', '', ''),
	(311, 'taunt', 'I like you. People say I have no taste, but I like you.', 0, 0, '', 'Je t\'aime bien. Les gens disent que je n\'ai pas de goût, mais je t\'aime bien.', '', '', '', '', '', ''),
	(312, 'taunt', 'I think you have an inferiority complex, but that\'s okay, it\'s justified.', 0, 0, '', 'Je pense que tu as un complexe d\'infériorité, mais il n\'y a pas de problème, c\'est justifié.', '', '', '', '', '', ''),
	(313, 'taunt', 'Hence rotten thing! Or I shall shake thy bones out of thy garments.', 0, 0, '', 'Par conséquent chose pourrie! Je vais secouer tes os de tes vêtements.', '', '', '', '', '', ''),
	(314, 'taunt', 'I can\'t believe I\'m wasting my time with you!', 0, 0, '', 'Je n\'arrive pas à croire que je perds mon temps avec toi!', '', '', '', '', '', ''),
	(315, 'taunt', 'I love it when someone insults me, it means I don\'t have to be nice anymore.', 0, 0, '', 'J\'adore quand quelqu\'un m\'insulte, ça veut dire que je n\'ai plus besoin d\'être gentil.', '', '', '', '', '', ''),
	(316, 'taunt', 'Thou leathern-jerkin, crystal-button, knot-pated, agatering, puke-stocking, caddis-garter, smooth-tongue, Spanish pouch!', 0, 0, '', 'Toi l\'agent fédéral, pourpoint en cuir, bouton de cristal, anneau d\'agate, bas vomi, jarretière caddis, pochette espagnole!', '', '', '', '', '', ''),
	(317, 'taunt', 'Thou qualling bat-fowling malt-worm!', 0, 0, '', 'Toi qualificatif de chauve-souris qui chasse le ver de malt!', '', '', '', '', '', ''),
	(318, 'taunt', 'Thou art truely an idol of idiot-worshippers!', 0, 0, '', 'Tu es vraiment une idole d\'adorateurs d\'idiots!', '', '', '', '', '', ''),
	(319, 'taunt', 'Thou misbegotten knotty-pated wagtail!', 0, 0, '', 'Tu es une bergeronnette printanière mal engendrée!', '', '', '', '', '', ''),
	(320, 'taunt', 'Thou whoreson mandrake, thou art fitter to be worn in my cap than to wait at my heels!', 0, 0, '', 'Toi putain de mandragore, tu es plus apte à être porté dans ma casquette qu\'à attendre sur mes talons!', '', '', '', '', '', ''),
	(321, 'taunt', 'You! You scullion! You rampallian! You fustilarian! I\'ll tickle your catastrophe!', 0, 0, '', 'Toi ! Espèce de marmiton ! Espèce de rampallian ! Espèce de fusilier ! Je vais chatouiller ta catastrophe!', '', '', '', '', '', ''),
	(322, 'taunt', 'Oh <target>! Thou infectious ill-nurtured flax-wench!', 0, 0, '', 'Oh <target>! Tu es contagieuse et mal nourrie!', '', '', '', '', '', ''),
	(323, 'taunt', 'We leak in your chimney, <target>!', 0, 0, '', 'On a une fuite dans votre cheminée, <target>!', '', '', '', '', '', ''),
	(324, 'taunt', 'Oh thou bootless fen-sucked canker-blossom!', 0, 0, '', 'Oh toi, fleur de chancre sucée par les marais sans botte!', '', '', '', '', '', ''),
	(325, 'taunt', 'Were I like thee I\'d throw away myself!', 0, 0, '', 'Si j\'étais comme toi, je me jetterais!', '', '', '', '', '', ''),
	(326, 'taunt', 'O teach me <target>, how I should forget to think!', 0, 0, '', 'O apprends-moi <target>, comme je devrais oublier de penser!', '', '', '', '', '', ''),
	(327, 'taunt', 'Truly thou art damned, like an ill-roasted egg, all on one side!', 0, 0, '', 'Vraiment tu es damné, comme un œuf mal rôti, tout d\'un côté!', '', '', '', '', '', ''),
	(328, 'taunt', 'You starvelling, you eel-skin, you dried neat\'s-tongue, you bull\'s-pizzle, you stock-fish- O for breath to utter what is like thee!! -you tailor\'s-yard, you sheath, you bow-case, you vile standing tuck!', 0, 0, '', 'Toi affamé, espèce de peau d\'anguille, ta langue bien séchée, espèce de taureau, poisson séché, O pour le souffle de dire ce qui te ressemble !! -espèce de vergue de tailleur, espèce de fourreau, espèce d\'étui à archet, vil tuck debout', '', '', '', '', '', ''),
	(329, 'taunt', 'Fie! Drop thee into the rotten mouth of Death!', 0, 0, '', 'Fi ! Jette-toi dans la bouche pourrie de la Mort!', '', '', '', '', '', ''),
	(330, 'taunt', '<target>, you are a fishmonger!', 0, 0, '', '<target>, vous êtes poissonnier!', '', '', '', '', '', ''),
	(331, 'taunt', 'I shall live to knock thy brains out!', 0, 0, '', 'Je vivrai pour te faire sauter la cervelle!', '', '', '', '', '', ''),
	(332, 'taunt', 'Most shallow are you, <target>!! Thou art worms-meat in respect of a good piece of flesh, indeed!!', 0, 0, '', 'Tu es très superficiel, <target>!! Tu es de la viande de vers par rapport à un bon morceau de chair, en effet!!', '', '', '', '', '', ''),
	(333, 'taunt', 'Vile wretch! O <target>, thou odiferous hell-hated pignut!', 0, 0, '', 'Misérable ! O <target>, toi, ignoble cochon de l\'enfer!', '', '', '', '', '', ''),
	(334, 'taunt', '<target>! Thy kiss is as comfortless as frozen water to a starved snake!', 0, 0, '', '<target>! Ton baiser est aussi désagréable que de l\'eau gelée pour un serpent affamé!', '', '', '', '', '', ''),
	(335, 'taunt', 'I scorn you, scurvy companion. What, you poor, base, rascally, cheating, lack-linen mate! Away, you moldy rogue, away!', 0, 0, '', 'Je te méprise, compagnon du scorbut. Quoi, pauvre, bas, coquin, tricheur, camarade en manque de linge ! Partez, espèce de voyou moisi, partez!', '', '', '', '', '', ''),
	(336, 'taunt', 'Out of my sight! Thou dost infect my eyes <target>!', 0, 0, '', 'Hors de ma vue! Tu infectes mes yeux <target>!', '', '', '', '', '', ''),
	(337, 'taunt', 'PLAY TIME!!!!', 0, 0, '', 'RÉCRÉATION!!!!', '', '', '', '', '', ''),
	(338, 'taunt', 'None shall pass!', 0, 0, '', 'Personne ne passera!', '', '', '', '', '', ''),
	(339, 'taunt', 'We\'re under attack! A vast, ye swabs! Repel the invaders!', 0, 0, '', 'Nous sommes attaqués ! Un vaste écouvillons! Repoussez les envahisseurs!', '', '', '', '', '', ''),
	(340, 'taunt', 'None may challenge the Brotherhood!', 0, 0, '', 'Personne ne peut défier la Confrérie!', '', '', '', '', '', ''),
	(341, 'taunt', 'Foolsss...Kill the one in the dress!', 0, 0, '', 'Foolsss... Tuez celui qui porte la robe!', '', '', '', '', '', ''),
	(342, 'taunt', 'I\'ll feed your soul to Hakkar himself! ', 0, 0, '', 'Je donnerai ton âme à Hakkar lui-même! ', '', '', '', '', '', ''),
	(343, 'taunt', 'Pride heralds the end of your world! Come, mortals! Face the wrath of the <randomfaction>!', 0, 0, '', 'La fierté annonce la fin de votre monde ! Venez, mortels ! Affrontez la colère des <randomfaction>!', '', '', '', '', '', ''),
	(344, 'taunt', 'All my plans have led to this!', 0, 0, '', 'Tous mes plans ont mené à cela!', '', '', '', '', '', ''),
	(345, 'taunt', 'Ahh! More lambs to the slaughter!', 0, 0, '', 'Ahhh ! Plus d\'agneaux à l\'abattoir!', '', '', '', '', '', ''),
	(346, 'taunt', 'Another day, another glorious battle!', 0, 0, '', 'Un autre jour, une autre bataille glorieuse!', '', '', '', '', '', ''),
	(347, 'taunt', 'So, business... or pleasure?', 0, 0, '', 'Alors, affaires... ou plaisir?', '', '', '', '', '', ''),
	(348, 'taunt', 'You are not prepared!', 0, 0, '', 'Vous n\'êtes pas prêt!', '', '', '', '', '', ''),
	(349, 'taunt', 'The <randomfaction>\'s final conquest has begun! Once again the subjugation of this world is within our grasp. Let none survive! ', 0, 0, '', 'La conquête finale de la <randomfaction> a commencé ! Une fois de plus, l\'assujettissement de ce monde est à notre portée. Que personne ne survive!', '', '', '', '', '', ''),
	(350, 'taunt', 'Your death will be a painful one. ', 0, 0, '', 'Ta mort sera douloureuse.', '', '', '', '', '', ''),
	(351, 'taunt', 'Cry for mercy! Your meaningless lives will soon be forfeit. ', 0, 0, '', 'Crie miséricorde ! Vos vies insignifiantes seront bientôt perdues.', '', '', '', '', '', ''),
	(352, 'taunt', 'Abandon all hope! The <randomfaction> has returned to finish what was begun so many years ago. This time there will be no escape! ', 0, 0, '', 'Abandonner tout espoir! La <randomfaction> est revenue pour terminer ce qui avait été commencé il y a tant d\'années. Cette fois, il n\'y aura pas d\'échappatoire!', '', '', '', '', '', ''),
	(353, 'taunt', 'Alert! You are marked for Extermination! ', 0, 0, '', 'Alerte! Vous êtes marqué pour l\'extermination!', '', '', '', '', '', ''),
	(354, 'taunt', 'The <subzone> is for guests only...', 0, 0, '', 'La <subzone> est réservée aux invités...', '', '', '', '', '', ''),
	(355, 'taunt', 'Ha ha ha! You are hopelessly outmatched!', 0, 0, '', 'Hahaha! Vous êtes désespérément surpassé!', '', '', '', '', '', ''),
	(356, 'taunt', 'I will crush your delusions of grandeur! ', 0, 0, '', 'Je vais écraser vos illusions de grandeur!', '', '', '', '', '', ''),
	(357, 'taunt', 'Forgive me, for you are about to lose the game.', 0, 0, '', 'Pardonnez-moi, car vous êtes sur le point de perdre la partie.', '', '', '', '', '', ''),
	(358, 'taunt', 'Struggling only makes it worse.', 0, 0, '', 'Lutter ne fait qu\'empirer les choses.', '', '', '', '', '', ''),
	(359, 'taunt', 'Vermin! Leeches! Take my blood and choke on it!', 0, 0, '', 'Vermine! sangsues ! Prends mon sang et étouffe-toi avec!', '', '', '', '', '', ''),
	(360, 'taunt', 'Not again... NOT AGAIN!', 0, 0, '', 'Pas encore... PAS ENCORE!', '', '', '', '', '', ''),
	(361, 'taunt', 'My blood will be the end of you!', 0, 0, '', 'Mon sang sera ta fin!', '', '', '', '', '', ''),
	(362, 'taunt', 'Good, now you fight me!', 0, 0, '', 'Bien, maintenant tu me combats!', '', '', '', '', '', ''),
	(363, 'taunt', 'Get da move on, guards! It be killin\' time!', 0, 0, '', 'Allez-y, gardes ! Ça va tuer le temps!', '', '', '', '', '', ''),
	(364, 'taunt', 'Don\'t be delayin\' your fate. Come to me now. I make your sacrifice quick.', 0, 0, '', 'Ne retardez pas votre destin. Viens à moi maintenant. Je fais votre sacrifice rapide.', '', '', '', '', '', ''),
	(365, 'taunt', 'You be dead soon enough!', 0, 0, '', 'Tu es mort bien assez tôt!', '', '', '', '', '', ''),
	(366, 'taunt', 'Mua-ha-ha!', 0, 0, '', 'Mua-ha-ha!', '', '', '', '', '', ''),
	(367, 'taunt', 'I be da predator! You da prey...', 0, 0, '', 'Je suis un prédateur ! Tu es une proie...', '', '', '', '', '', ''),
	(368, 'taunt', 'You gonna leave in pieces!', 0, 0, '', 'Tu vas partir en morceaux!', '', '', '', '', '', ''),
	(369, 'taunt', 'Death comes. Will your conscience be clear? ', 0, 0, '', 'La mort vient. Votre conscience sera-t-elle claire?', '', '', '', '', '', ''),
	(370, 'taunt', 'Your behavior will not be tolerated.', 0, 0, '', 'Votre comportement ne sera pas toléré.', '', '', '', '', '', ''),
	(371, 'taunt', 'The Menagerie is for guests only.', 0, 0, '', 'La Ménagerie est réservée aux invités.', '', '', '', '', '', ''),
	(372, 'taunt', 'Hmm, unannounced visitors, Preparations must be made... ', 0, 0, '', 'Hmm, visiteurs inopinés, il faut faire des préparatifs...', '', '', '', '', '', ''),
	(373, 'taunt', 'Hostile entities detected. Threat assessment protocol active. Primary target engaged. Time minus thirty seconds to re-evaluation.', 0, 0, '', 'Entités hostiles détectées. Protocole d\'évaluation de la menace actif. Cible principale engagée. Délai de réévaluation moins trente secondes.', '', '', '', '', '', ''),
	(374, 'taunt', 'New toys? For me? I promise I won\'t break them this time!', 0, 0, '', 'Nouveaux jouets? Pour moi? Promis je ne les casserai pas cette fois !', '', '', '', '', '', ''),
	(375, 'taunt', 'I\'m ready to play!', 0, 0, '', 'Je suis prêt à jouer!', '', '', '', '', '', ''),
	(376, 'taunt', 'Shhh... it will all be over soon.', 0, 0, '', 'Chut... tout sera bientôt fini.', '', '', '', '', '', ''),
	(377, 'taunt', 'Aaaaaughibbrgubugbugrguburgle!', 0, 0, '', 'Aaaaaughibbrgubugbugrguburgle!', '', '', '', '', '', ''),
	(378, 'taunt', 'RwlRwlRwlRwl!', 0, 0, '', 'RwlRwlRwlRwl!', '', '', '', '', '', ''),
	(379, 'taunt', 'You too, shall serve!', 0, 0, '', 'Toi aussi, tu serviras!', '', '', '', '', '', ''),
	(380, 'taunt', 'Tell me... tell me everything!  Naughty secrets! I\'ll rip the secrets from your flesh!', 0, 0, '', 'Dis-moi... dis-moi tout ! Secrets coquins ! J\'arracherai les secrets de ta chair!', '', '', '', '', '', ''),
	(381, 'taunt', 'Prepare yourselves, the bells have tolled! Shelter your weak, your young and your old! Each of you shall pay the final sum! Cry for mercy; the reckoning has come!', 0, 0, '', 'Préparez-vous, les cloches ont sonné ! Mettez à l\'abri vos faibles, vos jeunes et vos vieux ! Chacun de vous paiera la somme finale ! Implorez la miséricorde ; le jugement est venu!', '', '', '', '', '', ''),
	(382, 'taunt', 'Where in Bonzo\'s brass buttons am I?', 0, 0, '', 'Où suis-je dans les boutons en laiton de Bonzo?', '', '', '', '', '', ''),
	(383, 'taunt', 'I can bear it no longer! Goblin King! Goblin King! Wherever you may be! Take this <target> far away from me!', 0, 0, '', 'Je ne peux plus le supporter ! Roi Gobelin ! Roi Gobelin ! Où que vous soyez ! Emmenez cette <target> loin de moi!', '', '', '', '', '', ''),
	(384, 'taunt', 'You have thirteen hours in which to solve the labyrinth, before your baby brother becomes one of us... forever.', 0, 0, '', 'Vous avez treize heures pour résoudre le labyrinthe, avant que ton petit frère ne devienne l\'un des nôtres... pour toujours.', '', '', '', '', '', ''),
	(385, 'taunt', 'So, the <subzone> is a piece of cake, is it? Well, let\'s see how you deal with this little slice... ', 0, 0, '', 'Donc, la <subzone> est un jeu d\'enfant, n\'est-ce pas ? Eh bien, voyons comment tu gères cette petite tranche...', '', '', '', '', '', ''),
	(386, 'taunt', 'Back off, I\'ll take you on, headstrong to take on anyone, I know that you are wrong, and this is not where you belong', 0, 0, '', 'Reculez, je vais vous attaquer, têtu à affronter n\'importe qui, je sais que vous vous trompez, et ce n\'est pas votre place', '', '', '', '', '', ''),
	(387, 'taunt', 'Show me whatcha got!', 0, 0, '', 'Montre-moi ce que tu as!', '', '', '', '', '', ''),
	(388, 'taunt', 'To the death!', 0, 0, '', 'A la mort!', '', '', '', '', '', ''),
	(389, 'taunt', 'Twin blade action, for a clean close shave every time.', 0, 0, '', 'Action à double lame, pour un rasage de près propre à chaque fois.', '', '', '', '', '', ''),
	(390, 'taunt', 'Bring it on!', 0, 0, '', 'Allez-y!', '', '', '', '', '', ''),
	(391, 'taunt', 'You\'re goin\' down!', 0, 0, '', 'Tu descends!', '', '', '', '', '', ''),
	(392, 'taunt', 'Stabby stab stab!', 0, 0, '', 'Coup de poignard poignardé!', '', '', '', '', '', ''),
	(393, 'taunt', 'Let\'s get this over quick; time is mana.', 0, 0, '', 'Finissons-en vite ; le temps c\'est du mana.', '', '', '', '', '', ''),
	(394, 'taunt', 'I do not think you realise the gravity of your situation.', 0, 0, '', 'Je ne pense pas que tu te rendes compte de la gravité de ta situation.', '', '', '', '', '', ''),
	(395, 'taunt', 'I will bring honor to my family and my kingdom!', 0, 0, '', 'Je ferai honneur à ma famille et à mon royaume!', '', '', '', '', '', ''),
	(396, 'taunt', 'Light, give me strength!', 0, 0, '', 'Lumière, donne-moi la force!', '', '', '', '', '', ''),
	(397, 'taunt', 'My church is the field of battle - time to worship...', 0, 0, '', 'Mon église est le champ de bataille - il est temps d\'adorer...', '', '', '', '', '', ''),
	(398, 'taunt', 'I hold you in contempt...', 0, 0, '', 'Je te méprise...', '', '', '', '', '', ''),
	(399, 'taunt', 'Face the hammer of justice!', 0, 0, '', 'Affrontez le marteau de la justice!', '', '', '', '', '', ''),
	(400, 'taunt', 'Prove your worth in the test of arms under the Light!', 0, 0, '', 'Prouvez votre valeur dans l\'épreuve des armes sous la Lumière!', '', '', '', '', '', ''),
	(401, 'taunt', 'All must fall before the might and right of my cause, you shall be next!', 0, 0, '', 'Tout doit tomber devant la force et le droit de ma cause, vous serez le prochain!', '', '', '', '', '', ''),
	(402, 'taunt', 'Prepare to die!', 0, 0, '', 'Préparez-vous à mourir!', '', '', '', '', '', ''),
	(403, 'taunt', 'The beast with me is nothing compared to the beast within...', 0, 0, '', 'La bête avec moi n\'est rien comparée à la bête à l\'intérieur...', '', '', '', '', '', ''),
	(404, 'taunt', 'Witness the firepower of this fully armed huntsman!', 0, 0, '', 'Soyez témoin de la puissance de feu de ce chasseur entièrement armé!', '', '', '', '', '', ''),
	(405, 'critical health', 'Heal me! Quick!', 0, 0, '', 'Soigne moi! Vite!', '', '', '', '', '', ''),
	(406, 'critical health', 'Almost dead! Heal me!', 0, 0, '', 'Presque mort! Soigne moi!', '', '', '', '', '', ''),
	(407, 'critical health', 'Help! Heal me!', 0, 0, '', 'Aider! Soigne moi!', '', '', '', '', '', ''),
	(408, 'critical health', 'Somebody! Heal me!', 0, 0, '', 'Quelqu\'un! Soigne moi!', '', '', '', '', '', ''),
	(409, 'critical health', 'Heal! Heal! Heal!', 0, 0, '', 'Soigner! Soigner! Soigner!', '', '', '', '', '', ''),
	(410, 'critical health', 'I am dying! Heal! Aaaaarhg!', 0, 0, '', 'Je meurs! Soigner! Aaaaarhg!', '', '', '', '', '', ''),
	(411, 'critical health', 'Heal me!', 0, 0, '', 'Soigne moi!', '', '', '', '', '', ''),
	(412, 'critical health', 'I will die. I will die. I will die. Heal!', 0, 0, '', 'Je vais mourir. Je vais mourir. Je vais mourir. Soigner!', '', '', '', '', '', ''),
	(413, 'critical health', 'Healers, where are you? I am dying!', 0, 0, '', 'Guérisseurs, où êtes-vous ? Je meurs!', '', '', '', '', '', ''),
	(414, 'critical health', 'Oh the pain. Heal me quick!', 0, 0, '', 'Ah la douleur. Guéris-moi vite!', '', '', '', '', '', ''),
	(415, 'low health', 'Need heal', 0, 0, '', 'Besoin de guérir', '', '', '', '', '', ''),
	(416, 'low health', 'Low health', 0, 0, '', 'Santé faible', '', '', '', '', '', ''),
	(417, 'low health', 'Drop a heal. Please.', 0, 0, '', 'Dépose un soin. S\'il te plaît.', '', '', '', '', '', ''),
	(418, 'low health', 'Could somebody drop a heal on me?', 0, 0, '', 'Quelqu\'un pourrait-il me soigner?', '', '', '', '', '', ''),
	(419, 'low health', 'Hey! Better heal me now than rez later', 0, 0, '', 'Hey! Mieux vaut me soigner maintenant que rez plus tard', '', '', '', '', '', ''),
	(420, 'low health', 'I am sorry. Need another heal', 0, 0, '', 'Je suis désolé. J\'ai besoin d\'un autre soin', '', '', '', '', '', ''),
	(421, 'low health', 'Damn mobs. Heal me please', 0, 0, '', 'Maudits mobs. Guéris moi s\'il te plait', '', '', '', '', '', ''),
	(422, 'low health', 'One more hit and I am done for. Heal please', 0, 0, '', 'Un coup de plus et c\'est fini. Guéris moi s\'il te plait', '', '', '', '', '', ''),
	(423, 'low health', 'Are there any healers?', 0, 0, '', 'Y a-t-il des guérisseurs?', '', '', '', '', '', ''),
	(424, 'low health', 'Why do they always punch me in the face? Need heal', 0, 0, '', 'Pourquoi me frappent-ils toujours au visage? Besoin de soins', '', '', '', '', '', ''),
	(425, 'low health', 'Can anybody heal me a bit?', 0, 0, '', 'Quelqu\'un peut-il me guérir un peu?', '', '', '', '', '', ''),
	(426, 'low mana', 'OOM', 0, 0, '', 'MOO', '', '', '', '', '', ''),
	(427, 'low mana', 'I am out of mana', 0, 0, '', 'je n\'ai plus de mana', '', '', '', '', '', ''),
	(428, 'low mana', 'Damn I wasted all my mana on this', 0, 0, '', 'Putain j\'ai gaspillé tout mon mana sur ça', '', '', '', '', '', ''),
	(429, 'low mana', 'You should wait until I drink or regenerate my mana', 0, 0, '', 'Vous devriez attendre que je boive ou que je régénère mon mana', '', '', '', '', '', ''),
	(430, 'low mana', 'Low mana', 0, 0, '', 'Mana faible', '', '', '', '', '', ''),
	(431, 'low mana', 'No mana. Again?', 0, 0, '', 'Pas de mana. De nouveau?', '', '', '', '', '', ''),
	(432, 'low mana', 'Low mana. Wanna drink', 0, 0, '', 'Mana faible. Je veux boire', '', '', '', '', '', ''),
	(433, 'low mana', 'Do we have a vending machine? Out of mana again', 0, 0, '', 'Avons-nous un distributeur automatique? Plus de mana à nouveau', '', '', '', '', '', ''),
	(434, 'low mana', 'My mana is history', 0, 0, '', 'Mon mana appartient à l\'histoire', '', '', '', '', '', ''),
	(435, 'low mana', 'I\'d get some drinks next time. Out of mana', 0, 0, '', 'Je prendrais quelques verres la prochaine fois. Manque de mana', '', '', '', '', '', ''),
	(436, 'low mana', 'Where is my mana?', 0, 0, '', 'Où est mon mana?', '', '', '', '', '', ''),
	(437, 'aoe', 'Oh god!', 0, 0, '', 'Oh mon Dieu!', '', '', '', '', '', ''),
	(438, 'aoe', 'I am scared', 0, 0, '', 'j\'ai peur', '', '', '', '', '', ''),
	(439, 'aoe', 'We are done for', 0, 0, '', 'Nous avons fini pour', '', '', '', '', '', ''),
	(440, 'aoe', 'This is over', 0, 0, '', 'C\'est terminé', '', '', '', '', '', ''),
	(441, 'aoe', 'This ends now', 0, 0, '', 'Cela se termine maintenant', '', '', '', '', '', ''),
	(442, 'aoe', 'Could somebody cast blizzard or something?', 0, 0, '', 'Quelqu\'un pourrait-il lancer le blizzard ou quelque chose comme ça?', '', '', '', '', '', ''),
	(443, 'aoe', 'Damn. The tank aggroed all the mobs around', 0, 0, '', 'Mince. Le tank a agro toutes les mobs autour', '', '', '', '', '', ''),
	(444, 'aoe', 'We gonna die. We gonna die. We gonna die.', 0, 0, '', 'Nous allons mourir. Nous allons mourir. Nous allons mourir.', '', '', '', '', '', ''),
	(445, 'aoe', 'Whoa! So many toys to play with', 0, 0, '', 'Ouah ! Tant de jouets avec lesquels jouer', '', '', '', '', '', ''),
	(446, 'aoe', 'I gonna kill them all!', 0, 0, '', 'Je vais tous les tuer!', '', '', '', '', '', ''),
	(447, 'aoe', 'If the tank dies we are history', 0, 0, '', 'Si le tank meurt, nous appartenons à l\'histoire', '', '', '', '', '', ''),
	(448, 'aoe', 'Aaaaaargh!', 0, 0, '', 'Aaaaaargh!', '', '', '', '', '', ''),
	(449, 'aoe', 'LEEEEERROOOYYYYYYYYYYYY JENNKINNNSSSSSS!!!!!!!', 0, 0, '', 'LEEEEERROOOYYYYYYYYYYYY JENNKINNNSSSSSS!!!!!!!', '', '', '', '', '', ''),
	(450, 'aoe', 'Right. What do we have in AOE?', 0, 0, '', 'D\'accord. Qu\'avons-nous en dégats de zone?', '', '', '', '', '', ''),
	(451, 'aoe', 'This gets interesting', 0, 0, '', 'Cela devient intéressant', '', '', '', '', '', ''),
	(452, 'aoe', 'Cool. Get them in one place for a good flamestrike', 0, 0, '', 'Cool. Rassemblez-les au même endroit pour un bon coup de flamme', '', '', '', '', '', ''),
	(453, 'aoe', 'Kill! Kill! Kill!', 0, 0, '', 'Tuer! Tuer! Tuer!', '', '', '', '', '', ''),
	(454, 'aoe', 'I think my pants are wet', 0, 0, '', 'Je pense que mon pantalon est mouillé', '', '', '', '', '', ''),
	(455, 'aoe', 'We are history', 0, 0, '', 'Nous sommes l\'histoire', '', '', '', '', '', ''),
	(456, 'aoe', 'I hope healers are ready. Leeeeroy!', 0, 0, '', 'J\'espère que les guérisseurs sont prêts. Leeeeeroy!', '', '', '', '', '', ''),
	(457, 'aoe', 'I hope they won\'t come for me', 0, 0, '', 'j\'espère qu\'ils ont gagné, qu\'ils ne viendront pas pour moi', '', '', '', '', '', ''),
	(458, 'aoe', 'Oh no. I can\'t see at this slaugther', 0, 0, '', 'Oh non. Je ne peux pas voir à ce massacre', '', '', '', '', '', ''),
	(459, 'loot', 'I hope there will be some money', 0, 0, '', 'j\'espère qu\'il y aura de l\'argent', '', '', '', '', '', ''),
	(460, 'loot', 'Loot! Loot!', 0, 0, '', 'Butin! Butin!', '', '', '', '', '', ''),
	(461, 'loot', 'My precious', 0, 0, '', 'Mon précieux', '', '', '', '', '', ''),
	(462, 'loot', 'I hope there is a shiny epic item waiting for me there', 0, 0, '', 'J\'espère qu\'il y a un objet épique brillant qui m\'attend ici', '', '', '', '', '', ''),
	(463, 'loot', 'I have deep pockets and bags', 0, 0, '', 'J\'ai des poches et des sacs profonds', '', '', '', '', '', ''),
	(464, 'loot', 'All is mine!', 0, 0, '', 'Tout est à moi!', '', '', '', '', '', ''),
	(465, 'loot', 'Hope no gray shit today', 0, 0, '', 'J\'espère pas de merde grise aujourd\'hui', '', '', '', '', '', ''),
	(466, 'loot', 'This loot is MINE!', 0, 0, '', 'Ce butin est à MOI!', '', '', '', '', '', ''),
	(467, 'loot', 'Looting is disgusting but I need money', 0, 0, '', 'Le pillage est dégoûtant mais j\'ai besoin d\'argent', '', '', '', '', '', ''),
	(468, 'loot', 'Gold!', 0, 0, '', 'Or!', '', '', '', '', '', ''),
	(469, 'loot', 'OK. Let\'s see what they\'ve got', 0, 0, '', 'D\'ACCORD. Voyons ce qu\'ils ont', '', '', '', '', '', ''),
	(470, 'loot', 'Do not worry. I will loot eveything', 0, 0, '', 'Ne t\'inquiète pas. je vais tout piller', '', '', '', '', '', ''),
	(471, 'loot', 'I am loot ninja', 0, 0, '', 'je suis un ninja de butin', '', '', '', '', '', ''),
	(472, 'loot', 'Do I neeed to roll?', 0, 0, '', 'Dois-je recommencer?', '', '', '', '', '', ''),
	(473, 'loot', 'Somebody explain me, where they did put all this stuff?', 0, 0, '', 'Quelqu\'un m\'explique, où ils ont mis tout ça?', '', '', '', '', '', ''),
	(474, 'loot', 'No, I won\'t loot gray shit', 0, 0, '', 'Non, je ne pillerai pas la merde grise', '', '', '', '', '', ''),
	(475, 'loot', 'I\'m first. I\'m first. I\'m first.', 0, 0, '', 'Je suis le premier. Je suis le premier. Je suis le premier.', '', '', '', '', '', ''),
	(476, 'loot', 'Give me your money!', 0, 0, '', 'Donne-moi ton argent!', '', '', '', '', '', ''),
	(477, 'loot', 'My pockets are empty, I need to fill them', 0, 0, '', 'Mes poches sont vides, j\'ai besoin de les remplir', '', '', '', '', '', ''),
	(478, 'loot', 'I\'ve got a new bag for this', 0, 0, '', 'J\'ai un nouveau sac pour ça', '', '', '', '', '', ''),
	(479, 'loot', 'I hope I won\'t aggro anybody while looting', 0, 0, '', 'J\'espère que je n\'agresserai personne pendant le pillage', '', '', '', '', '', ''),
	(480, 'loot', 'Please don\'t watch. I am looting', 0, 0, '', 'S\'il vous plaît, ne regardez pas. je pille', '', '', '', '', '', ''),
	(481, 'loot', 'Ha! You won\'t get any piece of it!', 0, 0, '', 'Ha! Vous n\'en aurez aucun morceau!', '', '', '', '', '', ''),
	(482, 'loot', 'Looting is cool', 0, 0, '', 'Le pillage c\'est cool', '', '', '', '', '', ''),
	(483, 'loot', 'I like new gear', 0, 0, '', 'j\'aime le nouveau matos', '', '', '', '', '', ''),
	(484, 'loot', 'I\'l quit if there is nothing valuable again', 0, 0, '', 'J\'arrêterai s\'il n\'y a plus rien de précieux', '', '', '', '', '', ''),
	(485, 'loot', 'I hope it is be a pretty ring', 0, 0, '', 'j\'espère que c\'est une jolie bague', '', '', '', '', '', ''),
	(486, 'loot', 'I\'l rip the loot from you', 0, 0, '', 'Je t\'arracherai le butin', '', '', '', '', '', ''),
	(487, 'loot', 'Everybody stay off. I\'m going to loot', 0, 0, '', 'Tout le monde reste à l\'écart. je vais piller', '', '', '', '', '', ''),
	(488, 'loot', 'Sweet loot', 0, 0, '', 'Doux butin', '', '', '', '', '', ''),
	(489, 'loot', 'The Roll God! Give me an epic today', 0, 0, '', 'Le Dieu du rouleau ! Donnez-moi de l\'épique aujourd\'hui', '', '', '', '', '', ''),
	(490, 'loot', 'Please give me new toys', 0, 0, '', 'S\'il te plaît, donne-moi de nouveaux jouets', '', '', '', '', '', ''),
	(491, 'loot', 'I hope they carry tasties', 0, 0, '', 'J\'espère qu\'ils portent des saveurs', '', '', '', '', '', ''),
	(492, 'loot', 'The gold is mine. I\'l leave everyting, I promise', 0, 0, '', 'L\'or est à moi. Je laisse tout, je promets', '', '', '', '', '', ''),
	(493, 'loot', 'No, I can\'t resist', 0, 0, '', 'Non, je ne peux pas résister', '', '', '', '', '', ''),
	(494, 'loot', 'I want more!', 0, 0, '', 'Je veux plus!', '', '', '', '', '', ''),
	(495, 'low ammo', 'I have few <ammo> left!', 0, 0, '', 'Il me reste peu de <ammo>!', '', '', '', '', '', ''),
	(496, 'low ammo', 'I need more <ammo>!', 0, 0, '', 'J\'ai besoin de plus de <ammo>!', '', '', '', '', '', ''),
	(497, 'low ammo', '100 <ammo> left!', 0, 0, '', 'Il reste 100 <ammo>!', '', '', '', '', '', ''),
	(498, 'no ammo', 'That\'s it! No <ammo>!', 0, 0, '', 'C\'est ça! Pas de <ammo>!', '', '', '', '', '', ''),
	(499, 'no ammo', 'And you have my bow... Oops, no <ammo>!', 0, 0, '', 'Et vous avez mon arc... Oups, pas de <ammo>!', '', '', '', '', '', ''),
	(500, 'no ammo', 'Need ammo!', 0, 0, '', 'Besoin de munitions!', '', '', '', '', '', ''),
	(501, 'hello', 'Hello', 0, 0, '', 'Salut', '', '', '', '', '', 'Привет'),
	(502, 'hello', 'Hello!', 0, 0, '', 'Salut !', '', '', '', '', '', 'Привет!'),
	(503, 'hello', 'Hi', 0, 0, '', 'Bonjour', '', '', '', '', '', 'Прив'),
	(504, 'hello', 'Hi!', 0, 0, '', 'Bonjour !', '', '', '', '', '', 'Прив!'),
	(505, 'hello', 'Hello there!', 0, 0, '', 'Salut par ici !', '', '', '', '', '', 'Здарова!'),
	(506, 'hello_follow', 'Hello, I follow you!', 0, 0, '', 'Salut, je te suis !', '', '', '', '', '', 'Привет, иду за тобой!'),
	(507, 'hello_follow', 'Hello, lead the way!', 0, 0, '', 'Salut, après toi !', '', '', '', '', '', 'Привет, веди!'),
	(508, 'hello_follow', 'Hi, lead the way!', 0, 0, '', 'Bonjour, après vous !', '', '', '', '', '', 'Прив, веди!'),
	(509, 'logout_cancel', 'Logout cancelled!', 0, 0, '', 'Logout annulé', '', '', '', '', '', 'Логаут отменен!'),
	(510, 'logout_start', 'I\'m logging out!', 0, 0, '', 'Je déconnecte', '', '', '', '', '', 'Я выхожу из игры!'),
	(511, 'goodbye', 'Goodbye!', 0, 0, '', 'Au revoir', '', '', '', '', '', 'Пока!'),
	(512, 'goodbye', 'Bye bye!', 0, 0, '', 'Salut salut++', '', '', '', '', '', 'Пока пока!'),
	(513, 'goodbye', 'See you later!', 0, 0, '', 'A plus tard', '', '', '', '', '', 'Увидимся позже!'),
	(514, 'quest_accept', 'Quest accepted', 0, 0, '', 'Quête accepté', '', '', '', '', '', 'Квест взят'),
	(515, 'quest_remove', 'Quest removed', 0, 0, '', 'Quête supprimé', '', '', '', '', '', 'Квест отменен'),
	(516, 'quest_cant_take', 'I can\'t take this quest', 0, 0, '', 'Je ne peut pas prendre la quête', '', '', '', '', '', 'Я не могу взять этот квест'),
	(517, 'following', 'Following', 0, 0, '', 'Je vous suis', '', '', '', '', '', 'Следую'),
	(518, 'staying', 'Staying', 0, 0, '', 'Je reste en position', '', '', '', '', '', 'Стою'),
	(519, 'fleeing', 'Fleeing', 0, 0, '', 'Au secours !!', '', '', '', '', '', 'Убегаю'),
	(520, 'fleeing_far', 'I won\'t flee with you, you are too far away', 0, 0, '', 'Tu es trop loin je ne peut pas fuir avec toi', '', '', '', '', '', 'Я с тобой не побегу, ты слишком далеко'),
	(521, 'grinding', 'Grinding', 0, 0, '', 'Je grind', '', '', '', '', '', 'Гриндю'),
	(522, 'attacking', 'Attacking', 0, 0, '', 'J\'attack', '', '', '', '', '', 'Атакую'),
	(523, 'wait_travel_close', 'I am close, wait for me!', 0, 0, '', 'Attends moi je suis proche', '', '', '', '', '', 'Я тут рядом, подожди!'),
	(524, 'wait_travel_close', 'I\'m not far, please wait!', 0, 0, '', 'Je suis à côté s\'il te plait attends moi !', '', '', '', '', '', 'Я недалеко, погодите!'),
	(525, 'wait_travel_medium', 'I\'m heading to your location', 0, 0, '', 'J\'arrive sur ta position', '', '', '', '', '', 'Двигаюсь к тебе'),
	(526, 'wait_travel_medium', 'I\'m coming to you', 0, 0, '', 'Je viens à toi', '', '', '', '', '', 'Иду к тебе'),
	(527, 'wait_travel_far', 'I\'m traveling to your location', 0, 0, '', 'Je voyage jusqu\'à toi', '', '', '', '', '', 'Направляюсь к тебе'),
	(528, 'wait_travel_far', 'I\'m trying to get to you', 0, 0, '', 'J\'essai de vous rejoindre', '', '', '', '', '', 'Пытаюсь до тебя добраться'),
	(529, 'error_far', 'It is too far away', 0, 0, '', 'C\'est trop loin', '', '', '', '', '', 'Слишком далеко'),
	(530, 'error_water', 'It is under water', 0, 0, '', 'C\'est sous l\'eau', '', '', '', '', '', 'Это под водой'),
	(531, 'error_cant_go', 'I can\'t go there', 0, 0, '', 'Je ne peut pas atteindre cette destination', '', '', '', '', '', 'Я не могу туда пройти'),
	(532, 'error_guild', 'I\'m not in your guild!', 0, 0, '', 'Je ne fais pas parti de ta guilde', '', '', '', '', '', 'Я не в твоей гильдии'),
	(533, 'error_gbank_found', 'Can not find a guild bank nearby', 0, 0, '', 'Il n\'y a pas de coffre de guilde à proximité', '', '', '', '', '', 'Не могу найти гильд банк рядом'),
	(534, 'error_cant_put', 'I can\'t put ', 0, 0, '', '', '', '', '', '', '', 'Я не могу положить'),
	(535, 'error_gbank_rights', 'I have no rights to put items in the first guild bank tab', 0, 0, '', 'Je n\'ai pas les droits de dépôt à la banque', '', '', '', '', '', 'Нет прав чтобы класть вещи в первую вкладку гильд банка'),
	(536, 'gbank_put', ' put to guild bank', 0, 0, '', '', '', '', '', '', '', ' теперь в гильд банке');
/*!40000 ALTER TABLE `ai_playerbot_texts` ENABLE KEYS */;

DROP TABLE IF EXISTS `ai_playerbot_texts_chance`;

CREATE TABLE IF NOT EXISTS `ai_playerbot_texts_chance` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `probability` bigint(20) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=UTF8;

/*!40000 ALTER TABLE `ai_playerbot_texts_chance` DISABLE KEYS */;
INSERT INTO `ai_playerbot_texts_chance` (`id`, `name`, `probability`) VALUES
	(1, 'taunt', 30),
	(2, 'aoe', 75),
	(3, 'loot', 20);
/*!40000 ALTER TABLE `ai_playerbot_texts_chance` ENABLE KEYS */;