DROP TABLE IF EXISTS `playerbots_item_info_cache`;
CREATE TABLE IF NOT EXISTS `playerbots_item_info_cache` (
  `id` int(11) NOT NULL,
  `quality` int(11) DEFAULT NULL,
  `slot` int(11) DEFAULT NULL,
  `source` mediumint(8) DEFAULT NULL,
  `sourceId` mediumint(8) DEFAULT NULL,
  `team` mediumint(8) DEFAULT NULL,
  `faction` mediumint(8) DEFAULT NULL,
  `factionRepRank` mediumint(8) DEFAULT NULL,
  `minLevel` mediumint(8) DEFAULT NULL,
  `scale_1` mediumint(8) DEFAULT NULL,
  `scale_2` mediumint(8) DEFAULT NULL,
  `scale_3` mediumint(8) DEFAULT NULL,
  `scale_4` mediumint(8) DEFAULT NULL,
  `scale_5` mediumint(8) DEFAULT NULL,
  `scale_6` mediumint(8) DEFAULT NULL,
  `scale_7` mediumint(8) DEFAULT NULL,
  `scale_8` mediumint(8) DEFAULT NULL,
  `scale_9` mediumint(8) DEFAULT NULL,
  `scale_10` mediumint(8) DEFAULT NULL,
  `scale_11` mediumint(8) DEFAULT NULL,
  `scale_12` mediumint(8) DEFAULT NULL,
  `scale_13` mediumint(8) DEFAULT NULL,
  `scale_14` mediumint(8) DEFAULT NULL,
  `scale_15` mediumint(8) DEFAULT NULL,
  `scale_16` mediumint(8) DEFAULT NULL,
  `scale_17` mediumint(8) DEFAULT NULL,
  `scale_18` mediumint(8) DEFAULT NULL,
  `scale_19` mediumint(8) DEFAULT NULL,
  `scale_20` mediumint(8) DEFAULT NULL,
  `scale_21` mediumint(8) DEFAULT NULL,
  `scale_22` mediumint(8) DEFAULT NULL,
  `scale_23` mediumint(8) DEFAULT NULL,
  `scale_24` mediumint(8) DEFAULT NULL,
  `scale_25` mediumint(8) DEFAULT NULL,
  `scale_26` mediumint(8) DEFAULT NULL,
  `scale_27` mediumint(8) DEFAULT NULL,
  `scale_28` mediumint(8) DEFAULT NULL,
  `scale_29` mediumint(8) DEFAULT NULL,
  `scale_30` mediumint(8) DEFAULT NULL,
  `scale_31` mediumint(8) DEFAULT NULL,
  `scale_32` mediumint(8) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8 ROW_FORMAT=FIXED COMMENT='PlayerbotAI item info Cache';